### ISSUE TITLE
Add Debian 12 (bookworm) support

### ISSUE THREAD

**Issue by payne747** [nginxinc/nginx-amplify-agent#100]
Installation fails on Debian 12 (Bookworm) since there's no repository on `https://packages.amplify.nginx.com/` for Bookworm. 

Modifying `install.sh` to manually point to 'Buster' release works OK.

**Comment by wave84** [comment]
> Installation fails on Debian 12 (Bookworm) since there's no repository on `https://packages.amplify.nginx.com/` for Bookworm.
> 
> Modifying `install.sh` to manually point to 'Buster' release works OK.

Can you be more specific on what you modified inside the script to make it happen? I haven't managed to make it work so far, running into all kinds of errors. Thanks!

**Comment by ademaro** [comment]
apt woking only with
```
deb https://packages.amplify.nginx.com/py3/debian bullseye amplify-agent
```
in `/etc/apt/sources.list.d/nginx-amplify.list`

If you update the line for the new version: (for debian 12):
```
deb https://packages.amplify.nginx.com/py3/debian bookworm amplify-agent
```
Errors appear:
```
E: The repository 'https://packages.amplify.nginx.com/py3/debian bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
