### ISSUE TITLE
Adding Debian Testing aka Buster to supported systems

### ISSUE THREAD

**Issue by JamborJan** [nginxinc/nginx-amplify-agent#108]
I have one system running Debian Testing and was able to monkey patch the setup process for Nginx Amplify by manually adding the additional line for sources.list and commenting out the lines in the install.sh which would add a wrong line (as "buster" is not known the OS version is missing in the line).

Details of my monkey patch:
- ensure to have `deb https://packages.amplify.nginx.com/debian/ stretch amplify-agent` in your sources.list
- comment out these lines in install.sh: https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install.sh#L179-L192

Thats not a good solution at all but it works for now. Are there any specific reasons or requirements why Amplify is not available for buster?

Thanks.

**Comment by gshulegaard** [comment]
Hi @JamborJan, thanks for the information and your interest in the agent supporting more system environments!

To answer your question about why we don't support "buster" boils down to resources.  We try to prioritize system support by popularity.

Cheers!

**Comment by LordSimal** [comment]
Will Debian 10, aka Buster, be supported "soon" since it will release on 6th of July?

**Comment by LordSimal** [comment]
How about now since it has been released?

**Comment by alex-mohemian** [comment]
Can this be reopened?

@SeinopSys's workaround is great, but official support for the current stable Debian release would be great.

**Comment by defanator** [comment]
@alex-mohemian sure, we'll try to add Debian 10 as a supported platform. Thanks for the notice.

**Comment by Swiftnesses** [comment]
Looking forward to this being added! :)

**Comment by miroslavrussev** [comment]
I've tried @SeinopSys's workaround and it works. Thanks! 
I'm still waiting to get this official for Buster though. It sure makes sense since the nginx mainline docker image is based on "debian:buster-slim".

**Comment by defanator** [comment]
1.7.0-5 is now available for Debian 10.

**Comment by alex-mohemian** [comment]
@defanator thank you, that's awesome! Works just fine on Debian 10!

**Comment by MesoSource** [comment]
How can I install nginx amplify on debian 10?

**Comment by LordSimal** [comment]
@MesoSource 
see https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#installing-and-managing-nginx-amplify-agent
