### ISSUE TITLE
Fedora 28

### ISSUE THREAD

**Issue by rahilwazir** [nginxinc/nginx-amplify-agent#109]
By running the `install-source.sh` as sudo with 4th selection for Fedora 24,26, I get the following error:

```
...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl                                        
Installing collected packages: pip
Successfully installed pip-10.0.1
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl (567kB)                          
    100% |████████████████████████████████| 573kB 398kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 39.1.0
    Uninstalling setuptools-39.1.0:
      Successfully uninstalled setuptools-39.1.0
Successfully installed setuptools-39.2.0
Cloning into 'nginx-amplify-agent'...
remote: Counting objects: 3594, done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 3594 (delta 27), reused 107 (delta 19), pack-reused 3409
Receiving objects: 100% (3594/3594), 1.16 MiB | 428.00 KiB/s, done.
Resolving deltas: 100% (1941/1941), done.
Could not open requirements file: [Errno 2] No such file or directory: 'packages/requirements'
```

Also tried option 5th (Other), same error

**Comment by gshulegaard** [comment]
Hi Fedora 28 is not an officially supported distribution currently (https://amplify.nginx.com/docs/faq-2-nginx-amplify-agent.html), but thanks for you interest in Amplify and taking the time to report!

We will update here if we start to officially support Fedora 28.

**Comment by rahilwazir** [comment]
@gshulegaard Thanks for the reply.

Fedora 24,26 are listed as not fully supported versions and what would it take to support 27 or 28? The reported error does not indicate any dependency issues.

**Comment by gshulegaard** [comment]
Hi @rahilwazir!  We try to keep track of what systems are commonly requested to prioritize support so opening this issue is enough to put it on our radar.

**Comment by defanator** [comment]
@rahilwazir though there are no prebuilt packages for Fedora, latest agent version (1.8.0) is known to work with `install-source.sh` on at least Fedora 34 and 35. I'm going to close this one for now.
