### ISSUE TITLE
Adding public key failed during installation in nginx:1.15.4 docker container

### ISSUE THREAD

**Issue by saifat29** [nginxinc/nginx-amplify-agent#121]
I used the following two commands in my nginx Dockerfile to install amplify

1. curl -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh
OR wget https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh
2. API_KEY='HIDDEN' sh ./install.sh

But it fails on step 7. Adding public key ...(23) Failed writing body
failed.

This is the log
```bash
--- This script will install the NGINX Amplify Agent package ---
  1. Checking admin user ... root, ok.
  2. Checking API key ... using API_KEY(HIDDEN)
  3. Checking if uuid should be stored in the config ... False
  4. Checking Python ... found python 2.7
  5. Checking OS compatibility ... debian detected.
  6. Installing apt-transport-https ... done.
  7. Adding public key ...(23) Failed writing body
failed.
```

I checked the install.sh script, this is probably where the problem lies-
```bash
# Add public key for package verification (Ubuntu/Debian)
add_public_key_deb() {
    printf "\033[32m ${step}. Adding public key ...\033[0m"

    check_downloader && \
    ${downloader} ${downloader_opts} ${public_key_url} | \
    ${sudo_cmd} apt-key add - > /dev/null 2>&1

    if [ $? -ne 0 ]; then
        printf "\033[31m failed.\033[0m\n\n"
        exit 1
    else
        printf "\033[32m done.\033[0m\n"
    fi
}
```

**Comment by defanator** [comment]
@saifat29 could you please share your Dockerfile?

**Comment by saifat29** [comment]
@defanator 
Here is the Dockerfile
```Dockerfile
FROM nginx:1.15.4

RUN apt-get update \
    && apt-get install -y curl python \
    && curl -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh \
    && API_KEY='HIDDEN_API_KEY' sh ./install.sh

EXPOSE 80 443

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
```

**Comment by defanator** [comment]
@saifat29 thanks for sharing.

You should add the `gnupg` package to the list of preinstalled packages, i.e. `apt-get install -y curl python gnupg`. It is required in order to add nginx repository key to local apt keyring.

**Comment by saifat29** [comment]
@defanator Thanks nginx repository key is successfully added.
However now I get the following error
```bash
10. Installing nginx-amplify-agent package ... failed.

 Please check the list of the supported systems here https://git.io/vKkev
```
The nginx:1.15.4 image uses debian:stretch-slim which is clearly supported as specified here
https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-faq.md#21-what-operating-systems-are-supported

**Comment by defanator** [comment]
@saifat29 please add `-y` command line option to the `install.sh`, e.g. `API_KEY='HIDDEN_API_KEY' sh ./install.sh -y`.

**Comment by defanator** [comment]
Note that you'll also need to modify your Dockerfile to actually allow executing Amplify agent somehow (the `nginx` images are configured to launch `nginx -g "daemon off;"` by default).

**Comment by saifat29** [comment]
Thanks a lot. Have a nice day. 👍
