### ISSUE TITLE
Request: ngx_http_api_module available outside of Nginx+

### ISSUE THREAD

**Issue by fr8train-homebase** [nginxinc/nginx-amplify-agent#122]
I work for a smaller business (<50 employees) and we can't afford the pricing for basic level plans. I would love to see this added to the Nginx open source so we can use the full capacity of this awesome monitoring system.

**Comment by gshulegaard** [comment]
Thank you for taking the time to write up this feedback!

Just so you know, there are no additional metrics offered by the API module _itself_ that the Amplify agent cannot get from other sources like the access log.  There are several NGINX+ modules which expose custom metrics through the API module, but the API module itself doesn't add additional metrics.  The distinction is subtle, but I just want to assure you that every metric that we can possibly collect from NGINX open source and it's included modules, we do.

Something else to consider is that metrics gathered from logs have the benefit of also being structured data which allows for the creation of filters.  In case you haven't seen where this filter functionality lives, we offer it from our Dashboards area:

https://amplify.nginx.com/docs/guide-user-interface.html#dashboards

This filter functionality allows you to create more granular metrics based on request conditions using the structured nature of logs.

I want to emphasize that I appreciate your feedback and the time taken to provide it here; however, there is nothing actionable for my team with respect to the Amplify agent so I am going to close this ticket.  Please don't interpret this as a brush off of your feedback, I have made sure to pass it on to the appropriate people for consideration.  But there is little more I can do as simply a developer and maintainer for _Amplify_.
