### ISSUE TITLE
Nginx HTTP 500 Error

### ISSUE THREAD

**Issue by fr8train-homebase** [nginxinc/nginx-amplify-agent#124]
I created an alert to notify me of nginx.http.status.5xx errors and the alert worked great. But I didn't see a blip in the graphs or overview indicating that we had an HTTP 500 error. Can you help me figure out what's wrong?

**Comment by fr8train-homebase** [comment]
Never mind - just needed to give it some time.

**Comment by gshulegaard** [comment]
Well Thanks for taking the time to update!  I will go ahead and close this then.
