### ISSUE TITLE
problem loading repo

### ISSUE THREAD

**Issue by jaavid** [nginxinc/nginx-amplify-agent#128]
OS: Debian 8

Err https://packages.amplify.nginx.com jessie/amplify-agent amd64 Packages
  GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Ign https://packages.amplify.nginx.com jessie/amplify-agent Translation-en_US
Ign https://packages.amplify.nginx.com jessie/amplify-agent Translation-en
Fetched 227 kB in 20s (10.8 kB/s)
W: Failed to fetch https://packages.amplify.nginx.com/debian/dists/jessie/amplify-agent/binary-amd64/Packages  GnuTLS recv error (-110): The TLS connection was non-properly terminated.

E: Some index files failed to download. They have been ignored, or old ones used instead.

  8. Updating repository ... failed.

 Please check the list of the supported systems here https://git.io/vKkev

**Comment by defanator** [comment]
Closing this one as jessie is a long time EOL.
