### ISSUE TITLE
Last CentOS 7 build is not using SystemD service file

### ISSUE THREAD

**Issue by dvershinin** [nginxinc/nginx-amplify-agent#132]
In latest build of agent for CentOS 7, `nginx-amplify-agent.x86_64 1.4.1-1.el7`, it is still using init.d file instead of the `nginx-amplify-agent.service`, which I thought should be used based on the recent commits...

Confirm: 

```
$ repoquery -l nginx-amplify-agent | grep init.d
/etc/init.d/amplify-agent
```

And 

```
$ systemctl status amplify-agent
● amplify-agent.service - LSB: start and stop nginx-amplify-agent daemon
   Loaded: loaded (/etc/rc.d/init.d/amplify-agent; bad; vendor preset: disabled)
```

**Comment by defanator** [comment]
@dvershinin please update to the latest version (1.7.0-4).
