### ISSUE TITLE
amplify.agent.status = 0 over the past 5 min ?

### ISSUE THREAD

**Issue by chipitsine** [nginxinc/nginx-amplify-agent#138]
hello,

I would like to configure alert only if amplify.agent is not available over 5 min (or some other value)
amplify web interface allows me to specify any value, but it is changed to "2 min" when I save it

please, fix that. If you allow to save 5 min, it should be 5 min

**Comment by aluttik** [comment]
Hi,

For NGINX Amplify support, email amplify-support@nginx.com from the email you use for your account.

I'm going to close this because it is not an issue with the Amplify agent.

**Comment by chipitsine** [comment]
![screenshot from 2019-03-04 15-16-46](https://user-images.githubusercontent.com/2217296/53726839-aa024900-3e90-11e9-8e9a-dae8400e68b5.png)



your address is not configured to receive emails.
you are pushing me to do strange things

yes, I was trying to write from the address I am registered
