### ISSUE TITLE
how can I disable "Alerts during the past 60 minutes" ?

### ISSUE THREAD

**Issue by chipitsine** [nginxinc/nginx-amplify-agent#139]
hello,

I am confused, alerts come both online and "alerts during the past 60 minutes"
I found "alerts during the past 60 minutes" not useful
how can I disable them ?

**Comment by aluttik** [comment]
Hi,

For NGINX Amplify support, email amplify-support@nginx.com from the email you use for your account.

I'm going to close this because it is not an issue with the Amplify agent.
