### ISSUE TITLE
Email address listed under the "Support" menu in the dashboard doesn't work

### ISSUE THREAD

**Issue by janvitos** [nginxinc/nginx-amplify-agent#143]
Hi,

I encountered an issue today with NGINX Amplify and when I tried emailing amplify-support@nginx.com, the address found under the "Support" menu in the dashboard, my email was returned to me with the following error:

Address not found

Your message wasn't delivered to amplify-support@nginx.combecause the address couldn't be found or is unable to receive email.

The response from the remote server was:

554 5.7.1 <amplify-support@nginx.com>: Recipient address rejected: envelope-sender address is not listed as permitted for the request tracker. You are either do not bind email to support contract or From: address differ from envelope address

Thank you.

**Comment by defanator** [comment]
@janvitos could you please confirm that you've been using exactly the same email address you registered with in Amplify?

**Comment by janvitos** [comment]
I used a different email indeed. Could that be the issue?

**Comment by defanator** [comment]
@janvitos yes, support email channel has whitelist in place; whitelist is configured to accept only verified email addresses from Amplify users.

**Comment by janvitos** [comment]
Thanks for the info.

**Comment by mintjustin** [comment]
The whitelisting doesn't work with email delegated addresses. I registered an account with my email (gmail) which was delegated to another email account (also gmail). Even though I could send an email with sender being the email which was supposed to be whitelisted it get rejected anyway.  Is there a way to fix this or do I have to register my main email address to be able to get through?

**Comment by bcalik** [comment]
I have the same problem, and I've send the email from **exactly same email address** I registered to Amplify.
