### ISSUE TITLE
Raspbian support

### ISSUE THREAD

**Issue by modem7** [nginxinc/nginx-amplify-agent#148]
Hello, 

I run Nginx on my pi mainly for dev purposes.

I attempted to install and got the following:

  1. Checking admin user ... root, ok.
  2. Checking API key ... using <api key>
  3. Checking if uuid should be stored in the config ... False
  4. Checking Python ... found python 2.7
  5. Checking OS compatibility ... raspbian is currently unsupported, apologies!

If I try manual install, I get: W: The repository 'http://packages.amplify.nginx.com/raspbian stretch Release' does not have a Release file.

Would it be possible to have a packaged raspbian support for this at all? 

Thanks!

Edit: The alternative -source install script worked to install, but managing the package is certainly awkward having to do things like:

 sudo -u www-data python2.7 /usr/bin/nginx-amplify-agent.py start \
                   --config=/etc/amplify-agent/agent.conf \
                   --pid=/var/run/amplify-agent/amplify-agent.pid

 To stop the Amplify Agent use:

 sudo -u www-data python2.7 /usr/bin/nginx-amplify-agent.py stop \
                   --config=/etc/amplify-agent/agent.conf \
                   --pid=/var/run/amplify-agent/amplify-agent.pid

Also, how would one uninstall this package once built via the source script?

**Comment by leaskovski** [comment]
It would be good to have this package, but in the mean time I have installed from source as well.  Here are my steps I followed:

First we need to make sure we have the build components installed if we don't already have them:
```
sudo apt-get install git python python-dev wget gcc
```
Then we need to download the install from source script:
```
wget https://raw.githubusercontent.com/nginxinc/nginx-amplify-agent/master/packages/install-source.sh
```
Then we can launch the script with the API key taken from the Amplify website:
```
API_KEY='xxxxxxxxxxxxxxxxxx' sh ./install-source.sh
```
Now we want to create a service for it to run automatically:
```
sudo nano /etc/systemd/system/nginx-amplify-agent.service
```
Paste in the following systemd service definition:
```
[Unit]
Description=NGINX Amplify Agent
Documentation=https://amplify.nginx.com/docs/
After=network-online.target remote-fs.target nss-lookup.target
Wants=network-online.target

[Service]
Type=forking 
User=www-data
PIDFile=/var/run/amplify-agent/amplify-agent.pid
PermissionsStartOnly=true
ExecStart=/usr/bin/nginx-amplify-agent.py start --config=/etc/amplify-agent/agent.conf --pid=/var/run/amplify-agent/amplify-agent.pid
ExecStop=/usr/bin/nginx-amplify-agent.py stop --config=/etc/amplify-agent/agent.conf --pid=/var/run/amplify-agent/amplify-agent.pid

[Install]
WantedBy=multi-user.target
```
Then enable the services to start:
```
sudo systemctl enable /etc/systemd/system/nginx-amplify-agent.service
sudo systemctl start nginx-amplify-agent
```
Hope this helps someone else.

**Comment by djh1997** [comment]
What options did you pick as 5 for os didn't work for me

**Comment by leaskovski** [comment]
> What options did you pick as 5 for os didn't work for me

I used option 5.  It must be a dependency that is not installed for you.  What error did it spew out on compile?

**Comment by djh1997** [comment]
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-InigCj/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
       #include <ffi.h>
                ^~~~~~~
      compilation terminated.
      error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
[full dump](https://www.hawkins.engineer/amplify.txt)

**Comment by Kantudo** [comment]
> ```
>   arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-InigCj/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
>   c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>    #include <ffi.h>
>             ^~~~~~~
>   compilation terminated.
>   error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
> ```
> 
> [full dump](https://www.hawkins.engineer/amplify.txt)

I had the same problem as you, i found that you need to install libffi-dev, as it is required for building.

`sudo apt-get install libffi-dev`

**Comment by djh1997** [comment]
thanks that got me past that but not stuck here

> arm-linux-gnueabihf-gcc** -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-InigCj/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-armv7l-2.7/_openssl.c -o build/temp.linux-armv7l-2.7/build/temp.linux-armv7l-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion

>  build/temp.linux-armv7l-2.7/_openssl.c:546:10: fatal error: openssl/opensslv.h: No such file or directory
   #include <openssl/opensslv.h>
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
 > ----------------------------------------
>  ERROR: Failed building wheel for cryptography
Successfully built gevent netifaces psutil ujson setproctitle rstr flup scandir greenlet
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

**Comment by Kantudo** [comment]
great!, so you got it up and running then?

**Comment by modem7** [comment]
Have moved to Traefik, due to age of this issue (and that I totally forgot about it) will close issue unless someone else requires this functionality. 

Thank you for the assistance!

**Comment by McGeaverBeaver** [comment]
> ```
> sudo namo /usr/lib/tmpfiles.d/amplify-agent.conf
> ```

Spelling mistake but other than this worked great, easy copy-pasta! thank you.

**Comment by NL-TCH** [comment]
i changed the default python version from 2.7 to 3.7, so when i type python --version the output is 3.7.3.
the script gives the same error

(pip version automatically transfers to pip3 too)

**Comment by IMNotMax** [comment]
Same error here (same as [above](https://github.com/nginxinc/nginx-amplify-agent/issues/148#issuecomment-937666946))
Cannot install on a Raspberry Pi4
