### ISSUE TITLE
Cannot fetch system IO metrics.

### ISSUE THREAD

**Issue by Xdynix** [nginxinc/nginx-amplify-agent#152]
Nginx Version: 1.17.3
Amplify Agent Version: 1.7.0-4
OS: Centos 7

Problem:
There are no data for metrics related to disk IO (`system.io.kbs_r/w`, `system.io.wait_r/w` etc.). And the log file shows `sys_metrics sys_metrics failed to collect: disk_io_counters raised ValueError` every 20 seconds. The rest of the Amplify Agent is working properly.

I cannot find any information about this error. Any help would be greatly appreciated!

**Comment by kn007** [comment]
U need upgrade your psutil package

**Comment by Xdynix** [comment]
> U need upgrade your psutil package

Thanks for your reply!
It seems `psutil` is a python package, and I checked that it was not previously installed via yum or pip. I tried installed it manully for both python 2 and python 3. But it still not work. Do you mean to upgrade the psutil in the virtual environment of Amplify Agent (if there is any)? If so, where may I find the environment?

**Comment by kn007** [comment]
Yes, using pip with target
```
root@kn007:~
> pip install --upgrade --target=amplify --no-compile psutil
```

**Comment by Xdynix** [comment]
After looking into the installed files I found that Amplify Agent keeps copy of all its dependencies under the package location. In my case its `/usr/lib/python2.7/site-packages/amplify`. By changing into this directory and execute @kn007 's command `pip install --upgrade --target=. --no-compile psutil`, a newer version of `psutil` will replace the old one. Now there are no more error in the log file and the metric data finally come.

Thank you @kn007 !

**Comment by defanator** [comment]
@Xdynix could you please share what version of `psutil` you had before upgrading, and what one you've got after?

**Comment by kn007** [comment]
@Xdynix Don't mention it.
@defanator It seems amplify rpm using wrong psutil package.

**Comment by Xdynix** [comment]
@defanator Sorry for the late response. The `psutil` came with the Amplify Agent is version 4.0.0. Which I installed with pip is version 5.6.3. I use the install script mentioned in the Amplify docs. So it should come by yum.
