### ISSUE TITLE
phpfpm_meta - ls: cannot read symbolic link: permission denied

### ISSUE THREAD

**Issue by h3nrixd** [nginxinc/nginx-amplify-agent#153]
I have this repeating error in my agent.log:
```
2019-09-18 15:25:41,155 [9692] phpfpm_meta additional info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/master/meta.py", line 77, in bin_path
    ls, _ = subp.call(ls_cmd)
  File "/usr/lib/python2.7/dist-packages/amplify/agent/common/util/subp.py", line 32, in call
    raise AmplifySubprocessError(message=command, payload=dict(returncode=process.returncode, error=raw_err))
AmplifySubprocessError: (message=ls -la /proc/23739/exe, payload={'returncode': 2, 'error': "ls: cannot read symbolic link '/proc/23739/exe': Permission denied\n"})
```
my /proc directory is word readable dr-xr-xr-x
my /proc/23739 directory is word readable dr-xr-xr-x

my /proc/23739/exe link is word readable:
```
# ls -la /proc/23739/exe
lrwxrwxrwx 1 root root 0 Sep 18 16:01 /proc/23739/exe -> /usr/sbin/php-fpm7.2
```
my php-fpm binary is world readable:
`-rwxr-xr-x 1 root root 4869304 Aug 12 22:34 /usr/sbin/php-fpm7.2`

SELinux is not interfering

OS: Ubuntu 18.04.3 LTS
Agent: APT package nginx-amplify-agent 1.7.0-4~bionic from packages.amplify.nginx.com/ubuntu/ PPA

I also need to restart agents on my both servers about daily (seems bit random) because they stop updating stats. I don't get this error on my other server, so it is probably not related to this.

**Comment by mtx-z** [comment]
Encountered the same issue today. It may be bad but I run `sudo service amplify-agent restart` and it fixed the issue. I had PHP-FPM data displayed in my dashboards from this point.
