### ISSUE TITLE
Support for Ubuntu 19.04

### ISSUE THREAD

**Issue by peterbe** [nginxinc/nginx-amplify-agent#156]
I tried to install it on Ubuntu 19.04 but get this:
https://gist.github.com/peterbe/e4438b521708ac195b2c4cc34051ecbd
which links to https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-faq.md#21-what-operating-systems-are-supported

By filing this issue, hopefully, that'll cast at least 1 vote in favor of adding support for Ubuntu 19.04. (Also, it'll be my way of tracking if the support gets added)

**Comment by defanator** [comment]
@peterbe thanks for your attention. We're expecting a small update of agent package in upcoming weeks, introducing support for Ubuntu 19.04 as well.

**Comment by defanator** [comment]
@peterbe 1.7.0-5 version is now available for 19.04.
