### ISSUE TITLE
Support for CentOS 8

### ISSUE THREAD

**Issue by janvitos** [nginxinc/nginx-amplify-agent#157]
Hi,

The NGINX Amplify Agent doesn't seem to be supported on CentOS 8 yet. Do you have an idea when it will be?

Thanks.

**Comment by defanator** [comment]
@janvitos experimental build for RHEL/CentOS 8 has just appeared (1.7.0-5 package version).

**Comment by joelmacklow** [comment]
Hi @defanator. I've just tried to install this on a clean CentOS 8 vm with python27 and python36 installed and get this error when manually downloading and installing the RPM.
`[root@Test-CS-Host-01 ~]# rpm -ivh nginx-amplify-agent-1.7.0-5.el8.x86_64.rpm
error: Failed dependencies:
        python >= 2.6 is needed by nginx-amplify-agent-1.7.0-5.el8.x86_64
`
I can't locate a build of Python 2.6 for CentOS 8 though. Do you get this result too?

**Comment by defanator** [comment]
@joelmacklow there was the wrong dependency on python, fixed in https://github.com/nginxinc/nginx-amplify-agent/commit/8ec5fce96d45889f7da7f36123cc6d4f484c72e2. Updated package is available for testing. Let us know if you have any issues.
