### ISSUE TITLE
Unable to install nginx amplify agent

### ISSUE THREAD

**Issue by mazeeblanke** [nginxinc/nginx-amplify-agent#160]
I keep getting this error on ubuntu server, E: Package 'nginx-amplify-agent' has no installation candidate.

Here's what i have tried: 
1) curl -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh
2) API_KEY='key' sh ./install.sh

But the issues persists

**Comment by defanator** [comment]
@mazeeblanke which Ubuntu distro you were using? Latest agent version (1.8.0) is now Python 3 based and supports a number of modern distros:

https://amplify.nginx.com/docs/faq-2-nginx-amplify-agent.html#21-what-operating-systems-are-supported

I'm going to close this one for now.
