### ISSUE TITLE
 No module named 'amplify.agent'`

### ISSUE THREAD

**Issue by cell13** [nginxinc/nginx-amplify-agent#17]
os: CentOS release 6.5 (Final) 2.6.32-431.el6.x86_64
python version: 2.7.13
amplify-agent version: nginx-amplify-agent-0.46-2.el6.x86_64.rpm   
i have installed the nginx-amplify as the way in [amplify.nginx.com](https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent) step by step. I meet
the below problem when i trying starting amplify-agent. I try the pip command, but there is nothing work.
`tarting nginx-amplify-agent: Traceback (most recent call last):
  File "/usr/bin/nginx-amplify-agent.py", line 16, in <module>
    from amplify.agent.common.util import configreader
  File "/usr/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named agent.common.util`

**Comment by achawla2012** [comment]
Please update agent to latest version, which now comes with Python 3. https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent 
Closing this ticket. Please feel free to reopen if you see this problem after an update.
