### ISSUE TITLE
Update to python 3+

### ISSUE THREAD

**Issue by Cabur** [nginxinc/nginx-amplify-agent#175]
This requires python2.6/7 is there any plan to update since 2.7 has been depreciated, final release being 04/2020. Is there a timeline to update the install.sh to utilize 3?

**Comment by RvdE** [comment]
On FreeBSD Python 2.7 will expire after December 31st 2020. I've tried getting amplify agent to run on Python 3, but to no avail.

**Comment by defanator** [comment]
@Cabur @RvdE we've been working on porting latest agent code to Python 3; at this time, there's just one package available for Ubuntu 20.04 "focal", check this link for details: https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

Given that there still are platforms with Python 2.7 that we've committed to support earlier, most likely we will have two separate branches for py2 and py3 code. I don't have any estimates on when we would push py3 one to public repo, but you can check whether it works for you by trying Ubuntu 20.04 package by the above link.

**Comment by ulrikmoe** [comment]
@defanator 2.7 is long gone now, when will you migrate to Python 3? No offense, but an organization like Nginx shouldn't be in this level of code debt... I hope you'll fix this soon :)

**Comment by pydubreucq** [comment]
Hi,
Do you have an idea when Python 3 will be available ?
Python 2.6/2.7 isn't available on the latest Debian (11)
Best Regards,
Pierre-Yves Dubreucq

**Comment by defanator** [comment]
@Cabur @RvdE @ulrikmoe latest agent version (1.8.0) is now Python 3 based. Please follow the docs in order to upgrade:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent
