### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by LordSimal** [nginxinc/nginx-amplify-agent#177]
Since Ubuntu 20.04 has been released it would be awesome if the installer works with Ubuntu 20.04 aka "focal" as well.

Currently the installer spits out the following output:
```
-> % API_KEY='<my-API-key>' sh ./install.sh

 --- This script will install the NGINX Amplify Agent package ---

  1. Checking admin user ... you'll need sudo rights.
  2. Checking API key ... using <my-API-key>
  3. Checking if uuid should be stored in the config ... False
  4. Checking Python ... found python 2.7
  5. Checking OS compatibility ... ubuntu detected.
  6. Adding public key ... done.
  7. Adding repository ... added.
  8. Updating repository ...

Get:1 http://at.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Hit:2 http://ppa.launchpad.net/linux-schools/samba-latest/ubuntu focal InRelease                            
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease                                                                     
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                     
Hit:5 http://ppa.launchpad.net/wireguard/wireguard/ubuntu focal InRelease                                                                            
Get:6 http://at.archive.ubuntu.com/ubuntu focal-updates InRelease [89.1 kB]       
Hit:7 http://at.archive.ubuntu.com/ubuntu focal-backports InRelease                          
Get:8 http://at.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [648 B]
Get:9 http://at.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,004 B]
Ign:10 https://packages.amplify.nginx.com/ubuntu focal InRelease
Err:11 https://packages.amplify.nginx.com/ubuntu focal Release
  404  Not Found [IP: 52.24.43.197 443]
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

  8. Updating repository ... failed.

 Please check the list of the supported systems here https://git.io/vKkev
```

**Comment by LordSimal** [comment]
The main problem here is the fact, that the apt repository for the new "focal" Ubuntu version doesn't exist (yet).

I "fixed" this issue by forcing the "codename" in the install.sh to the older 18.04 (bionic) version.
![image](https://user-images.githubusercontent.com/9105243/80289336-0cc23e00-873e-11ea-860f-cd4ad0d2900e.png)

After that the installer was able to complete.

Therefore the current quickfix is forcing the codename version by adding this line in the install.sh

In the future it would be awesome if the DEVs would add the repository for 20.04 so it works with the correct codename in the /etc/apt//etc/apt/sources.list.d/nginx-amplify.list

**Comment by defanator** [comment]
@LordSimal please check https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

**Comment by jkldgoefgkljefogeg** [comment]
http://packages.amplify.nginx.com/ubuntu/dists/focal/ is not signed

```
E: The repository 'https://packages.amplify.nginx.com/ubuntu focal Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by defanator** [comment]
@jkldgoefgkljefogeg there's no such dist available under specified URI. Please check https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703 for details.

**Comment by deckblad** [comment]
We still don't have support for newer ubuntu versions. Now 20.10

Err:6 https://packages.amplify.nginx.com/ubuntu groovy Release
  404  Not Found [IP: 52.24.43.197 443]
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/ubuntu groovy Release' does not have a Release file.

**Comment by utkarshsystem** [comment]
Is there any update on this issue?

**Comment by defanator** [comment]
@utkarshsystem please check https://github.com/nginxinc/nginx-amplify-agent/issues/181#issuecomment-662107703

**Comment by defanator** [comment]
@LordSimal @utkarshsystem @jkldgoefgkljefogeg latest agent version (1.8.0) is now officially supports Ubuntu 20.04. Please follow the docs in order to upgrade:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent

**Comment by thommcgrath** [comment]
It's still showing as unsigned here:

```
Get:7 https://packages.amplify.nginx.com/ubuntu focal Release [3,278 B]             
Ign:8 https://packages.amplify.nginx.com/ubuntu focal Release.gpg
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/ubuntu focal Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

My source line is

```
deb https://packages.amplify.nginx.com/ubuntu/ focal amplify-agent
```

And the signing key is installed:

```
# sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa2048 2011-08-19 [SC] [expires: 2024-06-14]
      573B FD6B 3D8F BC64 1079  A6AB ABF5 BD82 7BD9 BF62
uid           [ unknown] nginx signing key <signing-key@nginx.com>
```

For what it's worth, this is an arm64 machine.

**Comment by defanator** [comment]
@thommcgrath you have wrong repoURI; correct one is:

```
deb https://packages.amplify.nginx.com/py3/ubuntu/ focal amplify-agent
```

**Comment by thommcgrath** [comment]
Thank you. The linked documentation should be updated then.

**Comment by defanator** [comment]
@thommcgrath the https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent link contains the note about changed paths for agent packages starting from version 1.8.0. Let us know if you think this should be elaborated somewhat further.

**Comment by thommcgrath** [comment]
Hmm. Ok, I guess I see the challenge. In my case I'm not updating, though I've used older versions on other servers. In this case, I'm setting up an ansible playbook to do the install so I was pulling the paths from the manual install instructions. Since I'm not updating the server, I wasn't really looking in that section of the install docs.

**Comment by erbanku** [comment]
The same problem still exists even after 2 years now.
``` --- This script will install the NGINX Amplify Agent package ---

  1. Checking admin user ... root, ok.
  2. Checking API key ... using 5084a7ca7c91aa1d6779c2efad00e875
  3. Checking if uuid should be stored in the config ... False
  4. Checking OS compatibility ... ubuntu detected.
  5. Checking Python ... found python 3.8
  6. Adding public key ... done.
  7. Adding repository ... added.
  8. Updating repository ...

Hit:1 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]             
Get:3 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]           
Ign:4 https://packages.amplify.nginx.com/py3//ubuntu focal InRelease                                   
Err:5 https://packages.amplify.nginx.com/py3//ubuntu focal Release                                     
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 52.24.43.197 443]
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease                                       
Reading package lists... Done                         
E: The repository 'https://packages.amplify.nginx.com/py3//ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

  8. Updating repository ... failed.

 Please check the list of the supported systems here https://git.io/vKkev```

**Comment by LordSimal** [comment]
@erbanku you should update your used ca-certificates with `sudo apt install ca-certificates`
as you see when you open https://packages.amplify.nginx.com/py3//ubuntu in a browser it has a valid HTTPS certificate.
your system just doesn't know how to connect to it because it uses outdated ca-certificates
