### ISSUE TITLE
Updating repository ... failed

### ISSUE THREAD

**Issue by Jarzka** [nginxinc/nginx-amplify-agent#179]
When running the install.sh, I get the following error:

```
W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

  8. Updating repository ... failed.
```

It seems that dockerproject.org has died. The following url http://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages says that:

> Notice: Shutting down dockerproject.org APT and YUM repos 2020-03-31
> 
> Docker will be shutting down the deprecated APT and YUM repositories hosted at "dockerproject.org" and "dockerproject.com" on the 31st of March 2020.
> 
> We noticed that this project is referencing one of these repositories, and recommend updating to use the "download.docker.com" repository to prevent disruption.
> 
> More info: https://www.docker.com/blog/changes-dockerproject-org-apt-yum-repositories/ 

I'm running Ubuntu 16.04, which should still be supported.

EDIT:

I was able to install the agent manually: https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#installing-the-agent-manually

**Comment by defanator** [comment]
@Jarzka closing this one as the reason is in another repository misconfiguration.
