### ISSUE TITLE
Missing requirements.txt file with python modules used

### ISSUE THREAD

**Issue by ddurieux** [nginxinc/nginx-amplify-agent#18]

**Comment by ddurieux** [comment]
I have installed with python2 setup.py install but gevent wasn't installed. I can too install with pip but a requirements file can be great to 

1. know the dependencies required
2. install automatically the dependents with pip

**Comment by dedm** [comment]
The correct way to install the agent is to use our install script or do it manually with provided packages, see https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#installing-amplify-agent

We have the requirements file: https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/requirements

**Comment by ddurieux** [comment]
Of course, but I install manually because install script not support FreeBSD :p

**Comment by dedm** [comment]
Oh, I see. Hope the file I provided above will help you!
