### ISSUE TITLE
error when starting the amplify-agent on ubuntu 20

### ISSUE THREAD

**Issue by lagassi** [nginxinc/nginx-amplify-agent#181]
when you typed the command # systemctl status amplify-agent.service, 
shows this

● amplify-agent.service - NGINX Amplify Agent
     Loaded: loaded (/lib/systemd/system/amplify-agent.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-07-06 02:16:39 UTC; 28s ago
       Docs: https://amplify.nginx.com/docs/
    Process: 7703 ExecStart=/etc/init.d/amplify-agent start (code=exited, status=1/FAILURE)

Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]:   File "/usr/lib/python2.7/dist-packages/amplify/gevent/builtins.py", line 93, in __import__
Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]:     result = _import(*args, **kwargs)
Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]:   File "/usr/lib/python2.7/dist-packages/amplify/agent/common/util/http.py", line 4, in <module>
Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]:     import ujson
Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]:   File "/usr/lib/python2.7/dist-packages/amplify/gevent/builtins.py", line 93, in __import__
Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]:     result = _import(*args, **kwargs)
Jul 06 02:16:39 leiloae-instance-1 amplify-agent[7742]: ImportError: /usr/lib/python2.7/dist-packages/amplify/ujson.so: undefined symbol: Buffer_AppendShortH>
Jul 06 02:16:39 leiloae-instance-1 systemd[1]: amplify-agent.service: Control process exited, code=exited, status=1/FAILURE
Jul 06 02:16:39 leiloae-instance-1 systemd[1]: amplify-agent.service: Failed with result 'exit-code'.
Jul 06 02:16:39 leiloae-instance-1 systemd[1]: Failed to start NGINX Amplify Agent.

**Comment by defanator** [comment]
@lagassi thank you for the report; while Ubuntu 20.04 is still officially unsupported, we're going to take a look and fix the agent.

**Comment by lagassi** [comment]
Thank you, I am waiting for the correction.

**Comment by dtalens** [comment]
Similar issue. 
`de jul. 14 19:13:57 minipc systemd[1]: Starting NGINX Amplify Agent...
de jul. 14 19:13:57 minipc amplify-agent[46259]: Config file /etc/amplify-agent/agent.conf could not be found or opened.
de jul. 14 19:13:57 minipc amplify-agent[46259]: If you installed the agent from the package you should do the following actions:
de jul. 14 19:13:57 minipc amplify-agent[46259]:   1. sudo cp /etc/amplify-agent/agent.conf.default /etc/amplify-agent/agent.conf
de jul. 14 19:13:57 minipc amplify-agent[46259]:   2. sudo chown nginx /etc/amplify-agent/agent.conf
de jul. 14 19:13:57 minipc amplify-agent[46259]:   3. write your API key in [credentials][api_key]
de jul. 14 19:13:57 minipc systemd[1]: amplify-agent.service: Control process exited, code=exited, status=1/FAILURE
de jul. 14 19:13:57 minipc systemd[1]: amplify-agent.service: Failed with result 'exit-code'.
de jul. 14 19:13:57 minipc systemd[1]: Failed to start NGINX Amplify Agent.
`
Bionic version works fine on ubuntu 20.04.

**Comment by defanator** [comment]
@lagassi @dtalens could you please try this package instead - https://packages.amplify.nginx.com/py3/ubuntu/pool/amplify-agent/n/nginx-amplify-agent/nginx-amplify-agent_1.8.0-1~focal_amd64.deb?

You can try to install it manually with `dpkg`, or via repository by slightly modified URL:

```
deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
```

Please note that 20.04 is not officially supported at the moment; consider this as an experimental build.

**Comment by dtalens** [comment]
Hello, 

Python 3 version of amplify agent works fine in ubuntu 20.04.

Thanks

**Comment by jkldgoefgkljefogeg** [comment]
Did api_url change? I am seeing HTTP 404 on api_url POST

```
2020-08-03 18:54:31,030 [139018] MainThread failed POST "https://receiver.amplify.nginx.com:443/1.4/API_KEY/agent/", exception: "404 Client Error: NOT FOUND for url: https://receiver.amplify.nginx.com:443/1.4/API_KEY/agent/"
```

**Comment by jebog** [comment]
> @lagassi @dtalens could you please try this package instead - https://packages.amplify.nginx.com/py3/ubuntu/pool/amplify-agent/n/nginx-amplify-agent/nginx-amplify-agent_1.8.0-1~focal_amd64.deb?
> 
> You can try to install it manually with `dpkg`, or via repository by slightly modified URL:
> 
> ```
> deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
> ```
> 
> Please note that 20.04 is not officially supported at the moment; consider this as an experimental build.

You can also edit manually install script to add this repository

**Comment by WarpWing** [comment]
![image](https://user-images.githubusercontent.com/28925758/91849865-af2d8900-ec2a-11ea-9fb6-166148b54765.png)
@defanator Here is what I get when I tried to install it. Should I open a new issue or can I get support from this one?

**Comment by defanator** [comment]
@WarpWing you can add the repository to avoid installing .deb manually - add this to `/etc/apt/sources.list.d/nginx-amplify-py3.list` and run `apt-get update && apt-get install nginx-amplify-agent` afterwards:

```
deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
```

**Comment by danijelk** [comment]
> @WarpWing you can add the repository to avoid installing .deb manually - add this to `/etc/apt/sources.list.d/nginx-amplify-py3.list` and run `apt-get update && apt-get install nginx-amplify-agent` afterwards:
> 
> ```
> deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
> ```
> 
> Alternatively, install all the prerequisites before you do `sudo dpkg -i ...`:
> 
> ```
> apt-get install python3-setproctitle python3-lockfile python3-daemon python3-greenlet python3-gevent python3-ujson python3-rstr python3-pymysql
> ```

Could you build it for arm64 as well so we can test and get back with results?

**Comment by Teranode** [comment]
works fine on my end, just changed the line:
`echo "deb ${packages_url}/${os}/ ${codename} amplify-agent"`
to 
`echo "deb ${packages_url}/py3/${os}/ ${codename} amplify-agent"`
![](https://i.imgur.com/R8AO1vY.png)

**Comment by nathanmillar16** [comment]
> > @WarpWing you can add the repository to avoid installing .deb manually - add this to `/etc/apt/sources.list.d/nginx-amplify-py3.list` and run `apt-get update && apt-get install nginx-amplify-agent` afterwards:
> > ```
> > deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
> > ```
> > 
> > 
> > Alternatively, install all the prerequisites before you do `sudo dpkg -i ...`:
> > ```
> > apt-get install python3-setproctitle python3-lockfile python3-daemon python3-greenlet python3-gevent python3-ujson python3-rstr python3-pymysql
> > ```
> 
> Could you build it for arm64 as well so we can test and get back with results?

I would also love it compiled for arm64. @danijelk Did you manage to get any further with it on arm64?

**Comment by danijelk** [comment]
> > > @WarpWing you can add the repository to avoid installing .deb manually - add this to `/etc/apt/sources.list.d/nginx-amplify-py3.list` and run `apt-get update && apt-get install nginx-amplify-agent` afterwards:
> > > ```
> > > deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
> > > ```
> > > 
> > > 
> > > Alternatively, install all the prerequisites before you do `sudo dpkg -i ...`:
> > > ```
> > > apt-get install python3-setproctitle python3-lockfile python3-daemon python3-greenlet python3-gevent python3-ujson python3-rstr python3-pymysql
> > > ```
> > 
> > 
> > Could you build it for arm64 as well so we can test and get back with results?
> 
> I would also love it compiled for arm64. @danijelk Did you manage to get any further with it on arm64?

No didn't do much more with it, was waiting for a sane reply :) @nathanmillar16 seems to have found the key though

**Comment by nathanmillar16** [comment]
> > > > @WarpWing you can add the repository to avoid installing .deb manually - add this to `/etc/apt/sources.list.d/nginx-amplify-py3.list` and run `apt-get update && apt-get install nginx-amplify-agent` afterwards:
> > > > ```
> > > > deb [arch=amd64] https://packages.amplify.nginx.com/py3/ubuntu focal amplify-agent
> > > > ```
> > > > 
> > > > 
> > > > Alternatively, install all the prerequisites before you do `sudo dpkg -i ...`:
> > > > ```
> > > > apt-get install python3-setproctitle python3-lockfile python3-daemon python3-greenlet python3-gevent python3-ujson python3-rstr python3-pymysql
> > > > ```
> > > 
> > > 
> > > Could you build it for arm64 as well so we can test and get back with results?
> > 
> > 
> > I would also love it compiled for arm64. @danijelk Did you manage to get any further with it on arm64?
> 
> No didn't do much more with it, was waiting for a sane reply :) @nathanmillar16 seems to have found the key though

@danijelk , what do you mean by 'seems to have found the key' ?

**Comment by rmadrona** [comment]
this package fixed sys_metrics problem on unbuntu-20.04 
https://packages.amplify.nginx.com/py3/ubuntu/pool/amplify-agent/n/nginx-amplify-agent/nginx-amplify-agent_1.8.0-1~focal_amd64.deb
I had same error https://github.com/nginxinc/nginx-amplify-agent/issues/171

**Comment by rmadrona** [comment]
@danijelk  do you have a package ready for arm64, I volunteer to test it on a fresh armbian release ?

**Comment by danijelk** [comment]
> @danijelk do you have a package or a fix ready for arm64, I volunteer to test it on a fresh armbian release ?
> sudo API_KEY='xxx' sh ./install.sh
> 5. Checking OS compatibility ... ubuntu detected.
> 
> Reading package lists... Done
> E: The repository 'https://packages.amplify.nginx.com/ubuntu focal Release' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> 
> 1. Updating repository ... failed.

Hey, yes arm has been working for a while.

/etc/apt/sources.list.d/nginx-amplify.list
deb https://packages.amplify.nginx.com/py3/ubuntu/ focal amplify-agent

As others mentioned in this thread, you can simply download the installer, replace

echo "deb ${packages_url}/${os}/ ${codename} amplify-agent"
to
echo "deb ${packages_url}/py3/${os}/ ${codename} amplify-agent"

and install it normally to get keys & scripts in the right place.

**Comment by rmadrona** [comment]
Thx @danijelk the fix almost works. I have now an error related to 15. Checking connectivity to the receiver ... failed to connect to the receiver! (check https://git.io/vKk0I)
Apparently  ${api_ping_url} is not responding, maybe maintenance going on. I will try later on
curl https://receiver.amplify.nginx.com:443/ping/
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by rmadrona** [comment]
Agent patch install.sh 
I ignore step 15. failed and can still run it on arm64 but still issue with os disk metrics
Does the arm64 package include the fix for disk_io_counters ?

tail -f /var/log/amplify-agent/agent.log
2021-05-10 20:30:27,231 [545116] sys_metrics sys_metrics failed to collect: disk_io_counters raised ValueError
2021-05-10 20:30:47,290 [545116] sys_metrics sys_metrics failed to collect: disk_io_counters raised ValueError

$ dpkg -s nginx-amplify-agent
Package: nginx-amplify-agent
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 1225
Maintainer: Andrei Belov <defan@nginx.com>
Architecture: arm64
Version: 1.8.0-1~focal
Depends: python3:any, python3-setproctitle, python3-lockfile, python3-daemon, python3-greenlet, python3-gevent, python3-requests, python3-ujson, python3-psutil, python3-rstr, python3-netifaces, python3-pymysql, lsb-release, adduser
Conffiles:
 /etc/amplify-agent/agent.conf.default c4831c94e00e9de9cf24bd14a040287c
 /etc/init.d/amplify-agent cac1488d95443fbc0b5f0eeb5da0d250
 /etc/logrotate.d/amplify-agent da238aa3d910729211814d1de3e9ed4c
Description: Agent for NGINX Amplify monitoring platform
 The NGINX Amplify Agent is a small, Python application that provides
 system and NGINX metric collection. It is part of NGINX Amplify -
 the monitoring and configuration assistance service for NGINX.
 .
 This package installs and runs NGINX Amplify Agent daemon.
 .
 See http://nginx.com/amplify for more information
Homepage: https://github.com/nginxinc/nginx-amplify-agent


$ sudo apt install python3-setproctitle python3-lockfile python3-daemon python3-greenlet python3-gevent python3-ujson python3-rstr python3-pymysql
[sudo] password for bob: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-greenlet is already the newest version (0.4.15-4.1).
python3-lockfile is already the newest version (1:0.12.2-2ubuntu2).
python3-lockfile set to manually installed.
python3-pymysql is already the newest version (0.9.3-2ubuntu3).
python3-setproctitle is already the newest version (1.1.10-1ubuntu1).
python3-daemon is already the newest version (2.2.4-1build1).
python3-gevent is already the newest version (1.4.0-1.2).
python3-rstr is already the newest version (2.2.6-2).
python3-ujson is already the newest version (1.35-4build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Nicholi** [comment]
A few minor modifications to install script and it should work as is on Ubuntu 20.04.

```
--- install_orig.sh	2021-07-06 22:14:37.030831977 +0000
+++ install.sh	2021-07-06 22:19:01.667272567 +0000
@@ -186,7 +186,7 @@
     ${sudo_cmd} test -w /etc/apt/sources.list.d && \
     ${sudo_cmd} rm -f /etc/apt/sources.list.d/amplify-agent.list && \
     ${sudo_cmd} rm -f /etc/apt/sources.list.d/nginx-amplify.list && \
-    echo "deb ${packages_url}/${os}/ ${codename} amplify-agent" | \
+    echo "deb ${packages_url}/py3/${os}/ ${codename} amplify-agent" | \
     ${sudo_cmd} tee /etc/apt/sources.list.d/nginx-amplify.list > /dev/null 2>&1 && \
     ${sudo_cmd} chmod 644 /etc/apt/sources.list.d/nginx-amplify.list > /dev/null 2>&1
 
@@ -376,9 +376,7 @@
 
 # Check for Python
 printf "\033[32m ${step}. Checking Python ...\033[0m"
-command -V python > /dev/null 2>&1 && python_bin='python'
-command -V python2.7 > /dev/null 2>&1 && python_bin='python2.7'
-command -V python2.6 > /dev/null 2>&1 && python_bin='python2.6'
+command -V python3 > /dev/null 2>&1 && python_bin='python3'
 
 if [ -z "${python_bin}" ]; then
     printf "\033[31m python 2.6 or 2.7 required, could not be found.\033[0m\n\n"
@@ -404,8 +402,8 @@
 python_version=`${python_bin} -c 'import sys; print("{0}.{1}".format(sys.version_info[0], sys.version_info[1]))'`
 
 if [ $? -eq 0 ]; then
-    if [ "${python_version}" != "2.6" -a "${python_version}" != "2.7" ]; then
-        printf "\033[31m python older than 2.6 or newer than 2.7 is not supported.\033[0m\n\n"
+    if ! echo "${python_version}" | grep -q '3\.[0-9]\+'; then
+        printf "\033[31m python older than 3.0 is not supported.\033[0m\n\n"
         exit 1
     fi
 else
```

**Comment by genimac** [comment]
Hello,
I'm trying to install it on my Debian 11 server.

- [ ] debian 11 current
- [ ] kernel  5.10
- [ ] nginx 1.18.0
- [ ] php 8.0.13
- [ ] mariadb 10.5.13

I follow the documentation and this tutorial [LEMP Stack Performance Monitoring with Nginx ](https://www.linuxbabe.com/monitoring/nginx-amplify-ubuntu)

Nginx, PHP 8 and system are working, all default graphs show.
Can't get Mariadb 10.5 to work.

my conf is as this
- [ ] [credentials]
- [ ] api_key = *******************
- [ ] hostname =
- [ ] uuid = 005b432af5ef53c9b2e60945fab95c89
- [ ] imagename =
- [ ] store_uuid = False
- [ ] [extensions]
- [ ] phpfpm = True
- [ ] mysql = True
- [ ] [mysql]
- [ ] unix_socket = /var/run/mysqld/mysqld.sock
- [ ] user = amplify-agent
- [ ] password = **********
- [ ] remote = False

socket exists:

- [ ] # ls /var/run/mysqld
- [ ] mysqld.pid  mysqld.sock

user has mysql access:
```
mysql -u amplify-agent -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.5.13-MariaDB-1:10.5.13+maria~bullseye-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show global status;
+--------------------------------------------------------+--------------------------------------------------+
| Variable_name                                          | Value                                            |
+--------------------------------------------------------+--------------------------------------------------+
| Aborted_clients                                        | 0                                                |
| Aborted_connects                                       | 4                                                |
| Aborted_connects_preauth                               | 0                                                |
| Access_denied_errors                                   | 4                                                |
| Acl_column_grants                                      | 0                                                |
more lines
| wsrep_provider_name                                    |                                                  |
| wsrep_provider_vendor                                  |                                                  |
| wsrep_provider_version                                 |                                                  |
| wsrep_ready                                            | OFF                                              |
| wsrep_rollbacker_thread_count                          | 0                                                |
| wsrep_thread_count                                     | 0                                                |
+--------------------------------------------------------+--------------------------------------------------+
571 rows in set (0.008 sec)
MariaDB [(none)]>
```
The tutorial have it working on Mariadb 10.1 as is show on a capture. I will like to try to get running on the 10.5 if possible, if not will install 10.1. Can I do something for it to work with 10.5?
Thanks

**Comment by defanator** [comment]
Latest agent version (1.8.0) is now officially supported on Ubuntu 20.04. Please follow the docs in order to upgrade:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent
