### ISSUE TITLE
agent will fail to detect nginx, ps(1) is restricted!

### ISSUE THREAD

**Issue by scyto** [nginxinc/nginx-amplify-agent#183]
I ran the install script inside my ngix container.

Only remaining error its:

```agent will fail to detect nginx, ps(1) is restricted!```
the logs show the agent started and connecting
the web site indeed shows that the agent failed to detect nginx, but is uploading system stats just fine.

the base container is the default nginx:latest from docker hub (i just attached a shell and ran the commands to install).

i tried adding
```user root;```
to my nginx conf (note it was set to ```# user nobody;``` before i did that.)
and the corresponding

```
user = root
configfile = /etc/nginx/nginx.conf
```
entry to the amplify-agent.conf to no avail.

**Comment by scyto** [comment]
this was my bad, the text editor i was using on the synology was not erroring when saving despite perms issue so entries appeared to disappear.

closing as my fault.

**Comment by podguzovvasily** [comment]
> this was my bad, the text editor i was using on the synology was not erroring when saving despite perms issue so entries appeared to disappear.
> 
> having root in the file in both locations fixed for now
> 
> closing as my fault.

I've added:

<code>user root;</code>

to the nginx.conf instead <code>user www-data;</code>

and add

<code>user = root</code>
<code>configfile = /etc/nginx/nginx.conf</code>

to the agent.conf

restarted both services but script show the same error "agent will fail to detect nginx, ps(1) is restricted!" What I'm doing wrong?

**Comment by scyto** [comment]
Is your nginx container running as root or did you change your perms or uid on the running container?

**Comment by podguzovvasily** [comment]
Yes as root, nothing was changed, official nginx:latest.

**Comment by podguzovvasily** [comment]
> Is your nginx container running as root or did you change your perms or uid on the running container?

I've also noticed, that all the time when I ran .sh, the [nginx] section in the agent.conf was cleared. I mean strings: 
<code>user = root</code> 
<code>configfile = /etc/nginx/nginx.conf</code>. So I guess it's the reason of the issue.

**Comment by podguzovvasily** [comment]
> Is your nginx container running as root or did you change your perms or uid on the running container?

Dear scyto, the issue was resolved by installing procpc.
