### ISSUE TITLE
Can't start nginx ampify agent

### ISSUE THREAD

**Issue by WarpWing** [nginxinc/nginx-amplify-agent#186]
Hello! So I just did the steps required (outputted by systemd) to start the nginx amplify service on Ubuntu 20.04. I got spitted out these errors. Any help?
```bash
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]: Traceback (most recent call last):
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]:   File "/usr/lib/python3/dist-packages/amplify/agent/main.py", line 145, in run
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]:     from amplify.agent.common.runner import Runner
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]:   File "/usr/lib/python3/dist-packages/amplify/agent/common/runner.py", line 4, in <module>
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]:     from daemon import runner
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]: ImportError: cannot import name 'runner' from 'daemon' (/usr/local/lib/python3.8/dist-packages/daemon.py)
Sep 02 00:40:51 v2202008126562124330 amplify-agent[779995]: Config file /etc/amplify-agent/agent.conf is OK
Sep 02 00:40:51 v2202008126562124330 systemd[1]: amplify-agent.service: Can't open PID file /run/amplify-agent/amplify-agent.pid (yet?) after start: Operation not permitted
Sep 02 00:40:51 v2202008126562124330 systemd[1]: amplify-agent.service: Failed with result 'protocol'.
Sep 02 00:40:51 v2202008126562124330 systemd[1]: Failed to start NGINX Amplify Agent.
[dev@v2202008126562124330 amplify-agent]$

**Comment by WarpWing** [comment]
Also, here is what happens if I start the service
```bash
[dev@v2202008126562124330 amplify-agent]$ sudo systemctl start amplify-agent.service
Job for amplify-agent.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status amplify-agent.service" and "journalctl -xe" for details.

**Comment by defanator** [comment]
@WarpWing please show an output of the following commands:

```
dpkg -s nginx-amplify-agent
dpkg -s python3-daemon
```

Thanks!

**Comment by WarpWing** [comment]
[dev@v2202008126562124330 ~]$ sudo dpkg -s nginx-amplify-agent
Package: nginx-amplify-agent
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 1225
Maintainer: Andrei Belov <defan@nginx.com>
Architecture: amd64
Version: 1.8.0-1~focal
Depends: python3:any, python3-setproctitle, python3-lockfile, python3-daemon, python3-greenlet, python3-gevent, python3-requests, python3-ujson, python3-psutil, python3-rstr, python3-netifaces, python3-pymysql, lsb-release, adduser
Conffiles:
 /etc/amplify-agent/agent.conf.default c4831c94e00e9de9cf24bd14a040287c
 /etc/init.d/amplify-agent cac1488d95443fbc0b5f0eeb5da0d250
 /etc/logrotate.d/amplify-agent da238aa3d910729211814d1de3e9ed4c
Description: Agent for NGINX Amplify monitoring platform
 The NGINX Amplify Agent is a small, Python application that provides
 system and NGINX metric collection. It is part of NGINX Amplify -
 the monitoring and configuration assistance service for NGINX.
 .
 This package installs and runs NGINX Amplify Agent daemon.
 .
 See http://nginx.com/amplify for more information
Homepage: https://github.com/nginxinc/nginx-amplify-agent
[dev@v2202008126562124330 ~]$ sudo dpkg -s python3-daemon
Package: python3-daemon
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 80
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: python-daemon
Version: 2.2.4-1build1
Depends: python3-pkg-resources, python3-lockfile, python3:any
Description: library for making a Unix daemon process — Python 3
 ‘daemon’ is a library that assists a Python program to turn itself
 into a well-behaved Unix daemon process, as specified in PEP 3143.
 .
 This library provides a ‘DaemonContext’ class that manages the
 following important tasks for becoming a daemon process:
 .
  * Detach the process into its own process group.
  * Set process environment appropriate for running inside a chroot.
  * Renounce suid and sgid privileges.
  * Close all open file descriptors.
  * Change the working directory, uid, gid, and umask.
  * Set appropriate signal handlers.
  * Open new file descriptors for stdin, stdout, and stderr.
  * Manage a specified PID lock file.
  * Register cleanup functions for at-exit processing.
 .
 This package installs the library for Python 3.
Original-Maintainer: Ben Finney <bignose@debian.org>
Homepage: https://pypi.python.org/pypi/python-daemon/

**Comment by defanator** [comment]
The 1.8.0 package for Ubuntu 20.04 "focal" has been fixed with the latest agent's update. Please follow the docs in order to upgrade from previous versions:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent
