### ISSUE TITLE
MySQL monitoring not working Mariadb 10.5.5

### ISSUE THREAD

**Issue by webigorkiev** [nginxinc/nginx-amplify-agent#188]
Hello. In the debug log error in ps xao pid,ppid,command | grep -E 'mysqld( |$)' 
supervisor failed to find running mysqld via "ps xao pid,ppid,command | grep -E 'mysqld( |$)'" due to AmplifySubprocessError

Debian 10.5
Mariadb 10.5.5
Agent version:
1.7.0-1

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/ext/mysql/managers.py", line 152, in _find_local
    ps, _ = (ps, None) if ps is not None else subp.call(PS_CMD)
  File "/usr/lib/python2.7/dist-packages/amplify/agent/common/util/subp.py", line 32, in call
    raise AmplifySubprocessError(message=command, payload=dict(returncode=process.returncode, error=raw_err))
AmplifySubprocessError: (message=ps xao pid,ppid,command | grep -E 'mysqld( |$)', payload={'returncode': 1, 'error': ''})
2020-09-21 09:28:53,976 [24014] supervisor mysql objects: []

**Comment by webigorkiev** [comment]
After reading the sources, it became clear - change /usr/sbin/ mariadb to
/usr/sbin/mysqld )))


Thanks for your attention

**Comment by thaidh1907** [comment]
> After reading the sources, it became clear - change /usr/sbin/ mariadb to
> /usr/sbin/mysqld )))
> 
> Thanks for your attention

can you show me how to fix ?

**Comment by webigorkiev** [comment]
Hello, mariadb in /lib/systemd/system/mysql.service exec /usr/sbin/mariadb - it's link for /usr/sbin/mysqld. 
For right work need /usr/sbin/mysqld
