### ISSUE TITLE
Error while install nginx-amplify-agent on Ubuntu 18.04

### ISSUE THREAD

**Issue by alaa-m** [nginxinc/nginx-amplify-agent#197]
Hello,

When I executed https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh  on Ubuntu 18.04 
I received this error :

 --- This script will install the NGINX Amplify Agent package ---

  1. Checking admin user ... root, ok.
  2. Checking API key ... using 00xxxxxxxxxxx
  3. Checking if uuid should be stored in the config ... False
  4. Checking Python ... found python 2.7
  5. Checking OS compatibility ... ubuntu detected.
  6. Adding public key ... done.
  7. Adding repository ... added.
  8. Updating repository ...

Hit:1 http://mirror.hetzner.de/ubuntu/packages bionic InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages bionic-backports InRelease
Hit:3 http://mirror.hetzner.de/ubuntu/packages bionic-security InRelease
Hit:4 http://mirror.hetzner.de/ubuntu/packages bionic-updates InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:6 http://de.archive.ubuntu.com/ubuntu bionic InRelease
Hit:7 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:8 http://de.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:9 https://packages.amplify.nginx.com/ubuntu bionic InRelease
Reading package lists... Done

  8. Updating repository ... done.
  9. Installing nginx-amplify-agent package ...

Reading package lists... Done
Building dependency tree
Reading state information... Done
nginx-amplify-agent is already the newest version (1.7.0-5~bionic).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

  9. Installing nginx-amplify-agent package ... done.
 10. Building configuration file ... can't find /etc/amplify-agent/agent.conf.default

Does anyone know why this error is happening??

Thank you.

**Comment by KingNonso** [comment]
[/etc/amplify-agent/agent.conf.default](https://github.com/nginxinc/nginx-amplify-agent/blob/master/etc/agent.conf.default)

Copy the file above and paste in `/etc/amplify-agent/agent.conf.default` (create the file if it doesn't exist)

**Comment by defanator** [comment]
@alaa-m thanks for reporting this. There was a misconfiguration in agent's post-removal scripts. The issue has been fixed in latest agent version (1.8.0). Please follow the docs in order to upgrade:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent
