### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Tenzer** [nginxinc/nginx-amplify-agent#2]
I am wondering if Python 3 support is something you accept patches for supporting, considering the list of operating systems you aim to support?
Many projects can support Python 2 and 3 at the same time as long as it's Python 2.6+ and 3.3+, but it requires some changes such as using `print` as a function, and taking care of any minor API changes between the versions.

**Comment by dedm** [comment]
Right now all supported operating systems use Python 2.6 or 2.7 by default. That is why the agent is written and packaged to work with 2.6 or 2.7. 
So Python 3 support is not a primary task, but we will accept patches for supporting.

**Comment by Tenzer** [comment]
Okay, that's understandable. Would you prefer to get more, smaller set of patches, changing one Python 3 incompatible thing at a time, or one big one to fix all the things in one go?

**Comment by Tenzer** [comment]
Sounds good to me. I have made the first patch in #4.
