### ISSUE TITLE
Couldn't start the agent, please check /var/log/amplify-agent/agent.log

### ISSUE THREAD

**Issue by jaiiali** [nginxinc/nginx-amplify-agent#21]
After installing the app completely, amplify-agent can not launched and following error occurred:

```
Couldn't start the agent, please check /var/log/amplify-agent/agent.log
```

After that, I want to start amplify-agent service manually, but the following error occurred:

```
Traceback (most recent call last):
  File "/usr/bin/nginx-amplify-agent.py", line 11, in <module>
    from gevent import monkey
  File "/usr/lib/python2.7/dist-packages/amplify/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 8, in <module>
    import greenlet  # http://pypi.python.org/pypi/greenlet/
ImportError: /usr/lib/python2.7/dist-packages/amplify/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
```

Finally, I checked the log file, but it was empty

I'm using latest version of Debian (8.5) and amplify-agent.

**Comment by dedm** [comment]
that's a bug with gevent, we will investigate it

**Comment by jaiiali** [comment]
but latest version of the Amplify work nicely on `ubuntu`

**Comment by valour01** [comment]
can not start the agent, either. Error log below:

    2016-06-22 23:06:51,028 [26959] MainThread configtest check
    2016-06-22 23:06:56,506 [26959] MainThread failed POST     "https://receiver.amplify.nginx.com:443/1.2/a67610ea268d2f7f8a03587670887382/agent/", exception: "HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Read timed out. (read timeout=5.0)"
    2016-06-22 23:06:56,506 [26959] MainThread post https://receiver.amplify.nginx.com:443/1.2/a67610ea268d2f7f8a03587670887382/agent/ 500 10 0 5.478

**Comment by gshulegaard** [comment]
Hi @valour01,

Your error is unrelated to the `gevent` bug for this thread.  Are you still having this issue?  If you are, I would be happy to (or you could) create a new issue for tracking.

Best,

**Comment by dedm** [comment]
@valour01 I deleted your comment cause it contained your API key. This morning we experienced some technical problems, that's why your agent couldn't start. Sorry about that. Try  to start agent now, it should work.

**Comment by dedm** [comment]
@jaiiali yes, it works well on ubuntu. We still have to investigate that issue with debian 8.5. Please bear with us

**Comment by jaiiali** [comment]
First, I run `apt-get update && apt-get install nginx-amplify-agent ` ,
After that, I was try to start the service: `/etc/init.d/amplify-agent start` 
but last error occurred

Do I need to run `apt-get dist-upgrade` before install/upgrade/start Amplify?

**Comment by valour01** [comment]
@dedm I see. But it still not work. I run `apt-get install nginx-amplify-agent` once again the error below:
>Reading package lists... Done
Building dependency tree       
Reading state information... Done
nginx-amplify-agent is already the newest version.
The following packages were automatically installed and are no longer required:
  golang-go-linux-amd64 golang-src libjs-jquery libntdb1 python-ntdb
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 151 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up nginx-amplify-agent (0.34-2~trusty) ...
dpkg: error processing package nginx-amplify-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 nginx-amplify-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jaiiali** [comment]
Yes, I upgraded the server from Debian 7.x to 8.x, but needed to run `apt-get dist-upgrade`!
I run this command and upgrade all packages of the server.
After that, the `nginx-amplify-agent` service start correctly 👍

**Comment by dedm** [comment]
@jaiiali great! Thanks for the explanation of this issue! May I close it then?

**Comment by jaiiali** [comment]
@dedm of course ;)
