### ISSUE TITLE
Add support Debian repo for bullseye

### ISSUE THREAD

**Issue by ademaro** [nginxinc/nginx-amplify-agent#211]
```sh
server# apt update
...
E: Репозиторий «http://packages.amplify.nginx.com/debian bullseye Release» не содержит файла Release.
N: Обновление из этого репозитория нельзя выполнить безопасным способом, поэтому по умолчанию он отключён.
N: Информацию о создании репозитория и настройках пользователя смотрите в справочной странице apt-secure(8).
```

**Comment by pydubreucq** [comment]
Hi,
Same need here :)
Best Regards,
Bye

**Comment by 00Mike00** [comment]
Hi, I managed to install it in a Bullseye system after 

1.  doing a change at the install.sh as @LordSimal shows at post #177 , but insteade of 'bionic' I typed **'buster'** , check the post to see how and where.

2. used the advice of @defanator from the post #181 and changed it a bit-> at /etc/apt/sources.list.d/nginx-amplify.list I changed it with 
deb https://packages.amplify.nginx.com/debian/ buster amplify-agent 

3.  sudo apt update

4. start the installation 

I must state that I am new in Debian and NginX, so their is a possibility not to reproduced something correct from what I have done to make it work. Hope I helped.

**Comment by kanaldro** [comment]
Any news here, @ciarams87, @lucacome, @ornj?

Is it EOL for Amplify? Should we drop Nginx Amplify and find other monitoring solution?

Thanks!

**Comment by defanator** [comment]
@kanaldro we are working on a number of updates in regards to support most recent Debian/Ubuntu distros, hopefully to have something later this month.

**Comment by kanaldro** [comment]
:heart_on_fire: Thanks!

**Comment by defanator** [comment]
@ademaro @kanaldro latest agent version (1.8.0) is now available for Debian 11 "bullseye". Please follow the documentation in order to upgrade from previous versions:

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#updating-the-agent

**Comment by No0ne** [comment]
@defanator seems not to be working, please check again:
```
Ign:4 https://packages.amplify.nginx.com/debian bullseye InRelease                
Err:5 https://packages.amplify.nginx.com/debian bullseye Release
  404  Not Found [IP: 52.24.210.11 443]
Reading package lists... Done
E: The repository 'https://packages.amplify.nginx.com/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by defanator** [comment]
@No0ne you have wrong repo URI, correct one for bullseye is:

```
deb https://packages.amplify.nginx.com/py3/debian bullseye amplify-agent
```

**Comment by No0ne** [comment]
Thanks 🙇‍♂️ its working!
