### ISSUE TITLE
failed to find master nginx process

### ISSUE THREAD

**Issue by tsabi** [nginxinc/nginx-amplify-agent#22]
I run nginx via supervisord, and because of this condition: ppid == 1 in the line below it cannot recognise the master process.
https://github.com/nginxinc/nginx-amplify-agent/blob/master/amplify/agent/managers/nginx.py#L206

The internally used ps output on the host it fails:
 2456  1743 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
11077  2456 nginx: worker process
11078  2456 nginx: worker process

Another host where nginx runs via systemd:
20852     1 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
20853 20852 nginx: worker process
20854 20852 nginx: worker process
20855 20852 nginx: worker process
20856 20852 nginx: worker process

**Comment by dedm** [comment]
Do you use supervisord in the first case?
