### ISSUE TITLE
Alpine Linux Support

### ISSUE THREAD

**Issue by willfarrell** [nginxinc/nginx-amplify-agent#24]
Would love to have this extend nginx:1-alpine docker image.

**Comment by dedm** [comment]
Soon we will provide a step-by-step manual "How to install NGINX Amplify Agent if your OS is not supported". Hope it will help.

**Comment by dedm** [comment]
@willfarrell we released a beta script for installing agent in non-supported systems: https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh 

Please try it and tell us how was it.

**Comment by willfarrell** [comment]
Awesome, hopefully I can find some time to play around with it.
