### ISSUE TITLE
runsv support

### ISSUE THREAD

**Issue by Ferrisbane** [nginxinc/nginx-amplify-agent#28]
The GitLab omnibus runs nginx with the runsv launcher.

Currently runsv is not supported, however I am sure many GitLab users will find nginx amplify a very useful service (including me).

Is there anything needed to be updated with the agent to allow this?
I am able to test/dev necessary changes if needed.

Thanks.

**Comment by dedm** [comment]
Hi!

We know about the issue with runsv. Actually it's the same problem we had with supervisord and it was successfully solved in the latest release (0.36). We will implement runsv support in one of the next releases, but right now you can try to fix it yourself.   

Just modify this line https://github.com/nginxinc/nginx-amplify-agent/blob/master/amplify/agent/managers/nginx.py#L23, add runsv there  and restart the agent. 

Please tell us if this solution worked for you.

Best,
Mike

**Comment by Ferrisbane** [comment]
Adding to agent/manager/nginx.py launcher array works perfectly fine, now showing nginx data on website.

Thanks.

**Comment by dedm** [comment]
I reopened this issue to close it after we add runsv support to the source code

**Comment by Ferrisbane** [comment]
Ah sorry :)
