### ISSUE TITLE
Recurring entries in error log after deploying the nginx-amplify agent

### ISSUE THREAD

**Issue by schallertd** [nginxinc/nginx-amplify-agent#29]
Hi,

i'm seeing the following lines appearing in nginx's error log periodically with the latest nginx-amplify-agent on Debian Jessie:

	root@web38 ~ # tail -f /var/log/nginx/error.log
	2016/07/30 06:00:32 [warn] 25734#25734: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
	2016/07/30 06:00:32 [emerg] 25734#25734: SSL_CTX_use_PrivateKey_file("/etc/ssl/private/xxx.com.key") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/ssl/private/xxx.com.key','r') error:20074002:BIO routines:FILE_CTRL:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)

Since the config test passes and this error hadn't been there before, I do strongly believe it's a issue related to the current nginx-amplify-agent version.  I've also already tried to switch the user of the amplify agent between www-data and root  and even changed the ssl cert and key permissions to 777, but nothing stopped those lines from appearing.

Some diagnostics:

	root@web38 ~ # nginx -v
	nginx version: nginx/1.11.3

	root@web38 ~ # nginx -t
	nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
	nginx: configuration file /etc/nginx/nginx.conf test is successful

	root@web38 ~ # ps faux | grep nginx
	root     15988  0.0  0.4  84252 36388 ?        Ss   01:04   0:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
	www-data 15989  0.0  0.4  84256 40248 ?        S    01:04   0:00  \_ nginx: worker process                   
	www-data 15991  0.0  0.4  84256 39896 ?        S    01:04   0:00  \_ nginx: worker process                   
	www-data 15993  0.0  0.4  84256 40060 ?        S    01:04   0:00  \_ nginx: worker process                   
	www-data 15995  0.0  0.4  84256 40756 ?        S    01:04   0:00  \_ nginx: worker process                   
	www-data 15997  0.0  0.4  84256 40536 ?        S    01:04   0:00  \_ nginx: worker process                   
	www-data 15999  0.0  0.4  84256 40876 ?        S    01:04   0:00  \_ nginx: worker process                   
	www-data 16001  0.1  0.5  84552 41344 ?        S    01:04   0:01  \_ nginx: worker process                   
	www-data 16003  0.0  0.5  84256 41060 ?        S    01:04   0:01  \_ nginx: worker process 

	root@web38 ~ # ps aux | grep amplify
	www-data 19177 15.7  0.4  95128 38924 ?        S    01:31   0:10 amplify-agent  

First question would be, why nginx-amplify-agent wants to access my private.key? I don't really get the point because the `ssl_certificate_key` directive seems to be listed in the `IGNORED_DIRECTIVES` list in https://github.com/nginxinc/nginx-amplify-agent/blob/3d3192db60034a8ba0a2ab42d57355145318062e/amplify/agent/objects/nginx/config/parser.py#L27

Furthermore I've just removed the nginx-amplify-agent again from a few boxes for testing purposes and suddenly the lines above seem to be gone aswell.

Thanks in advance
@schallertd

**Comment by dedm** [comment]
Hi, 

By default Agent tries to run "nginx -t" command. Sometimes it's not possible (when agent user doesn't have proper permissions) and in that case nginx will write those messages in the error log.

Amplify agent doesn't try to access your private key. This is nginx who tries to run config test (nginx -t command).

You can disable automatic config checking in Amplify UI (Options -> Settings -> Enable automatic config checking). 

Best,
@dedm

**Comment by schallertd** [comment]
Hi Mike,
thanks for the hint. Just checked and I can confirm that the log entries seem to be caused by nginx-amplify performing the automatic config checks with  ´nginx -t´ as www-data user. After disabling the config checks within the Amplify UI, the log entries seem to be gone.

Issue resolved, thank you very much.
Kind Regards
