### ISSUE TITLE
SuSE not supported

### ISSUE THREAD

**Issue by dkrotil** [nginxinc/nginx-amplify-agent#30]
Hi , second largest Linux corp in the world isn´t supported, can you add support for SuSE ?

Thanks

**Comment by dedm** [comment]
Soon we will provide a step-by-step manual "How to install NGINX Amplify Agent if your OS is not supported". Hope it will help.

**Comment by dedm** [comment]
@dkrotil  we released a beta script for installing agent in non-supported systems: https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh 

Please try it and tell us how it was.

**Comment by dkrotil** [comment]
Tested on SLES12 SP1, looks ok.

**Comment by dedm** [comment]
Thanks for the report. This bug will be fixed in the next release (0.39). We're planning to release it on Sep 20 or 21. Please bear with us!
