### ISSUE TITLE
OpenResty support

### ISSUE THREAD

**Issue by guizmaii** [nginxinc/nginx-amplify-agent#31]
Does it support OpenResty ? 

I installed amplify-agent on one of my OpenResty server. I have the metrics but not the "reports".

**Comment by dedm** [comment]
Hi @guizmaii 

May I ask you to download and run the following script and send me its output via email?
https://raw.githubusercontent.com/nginxinc/nginx-amplify-agent/master/packages/collect-env.sh

Also please send me  /var/log/amplify-agent/agent.log

**Comment by dedm** [comment]
Also, please install the latest version (0.41), it has fixes for OpenResty support
