### ISSUE TITLE
Gentoo support

### ISSUE THREAD

**Issue by hnaparst** [nginxinc/nginx-amplify-agent#32]
I have written ebuilds for Gentoo. However they are giving the error

```
File "/usr/lib64/python2.7/site-packages/amplify/agent/common/util/loader.py", line 17, in import_class
    return getattr(module, class_name)
AttributeError: 'module' object has no attribute 'GentooNginxMetaCollector'
```

If you want to try the ebuilds, do this:

```

# layman -a hnaparst
# layman -S
# emerge nginx-amplify-agent

```

**Comment by hnaparst** [comment]
I have sent you a pull request for Gentoo.  It works for me now with those changes.

**Comment by dedm** [comment]
@hnaparst  we released a beta script for installing agent, now with Gentoo support: https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh

Please try it and tell us how it was.
