### ISSUE TITLE
Debian 8.6 OpenSSL Error

### ISSUE THREAD

**Issue by Knight1** [nginxinc/nginx-amplify-agent#35]
Hey,

I get everytime the following error.

`Process: 27027 ExecStart=/etc/init.d/amplify-agent start (code=exited, status=1/FAILURE)`

`Oct 27 00:38:54 main amplify-agent[27027]: File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>`
`Oct 27 00:38:54 main amplify-agent[27027]: from OpenSSL._util import (
Oct 27 00:38:54 main amplify-agent[27027]: File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 3, in <module>
Oct 27 00:38:54 main amplify-agent[27027]: from cryptography.hazmat.bindings.openssl.binding import Binding`
`Oct 27 00:38:54 main amplify-agent[27027]: File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
Oct 27 00:38:54 main amplify-agent[27027]: from cryptography.hazmat.bindings._openssl import ffi, lib`
`Oct 27 00:38:54 main amplify-agent[27027]: AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'`
`Oct 27 00:38:54 main systemd[1]: amplify-agent.service: control process exited, code=exited status=1
Oct 27 00:38:54 main systemd[1]: Failed to start LSB: Stop/start nginx-amplify-agent.
Oct 27 00:38:54 main systemd[1]: Unit amplify-agent.service entered failed state.`

OS Debian 8.6 is up to date
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
OpenSSL 1.0.1t  3 May 2016

The installed encountered the following problem:
`15. Checking system time with ntpdate(8) ... failed - no ntpdate installed!`
This is a systemD Linux Version. Therefore there is no ntpdate or service anymore.

/var/log/amplify-agent/agent.log is empty.

Hope you can help me :)

**Comment by dedm** [comment]
Hi, @Knight1 

Can you provide the version of python-cryptography package?

**Comment by Knight1** [comment]
Sure @dedm 

`dpkg -s python-cryptography`
`Package: python-cryptography`
`Status: install ok installed`
`Priority: optional`
`Section: python`
`Installed-Size: 1082`
`Maintainer: Tristan Seligmann <mithrandi@debian.org>`
`Architecture: amd64`
`Version: 0.6.1-1`
`Depends: python:any (>= 2.7.5-5~), python-cffi, python (>= 2.7~), python (<< 2.8), python-pkg-resources, python-six, libc6 (>= 2.4), libssl1.0.0 (>= 1.0.1)`
`Suggests: python-cryptography-doc, python-cryptography-vectors`

`dpkg -s python-openssl`
`Package: python-openssl`
`Status: install ok installed`
`Priority: optional`
`Section: python`
`Installed-Size: 368`
`Maintainer: Sandro Tosi <morph@debian.org>`
`Architecture: all`
`Source: pyopenssl`
`Version: 0.14-1`
`Depends: python:any (>= 2.7.5-5~), python-cryptography, python-six, python:any (<< 2.8)`

`dpkg-query -l | grep ssl`
`ii  docbook-dsssl                        1.79-7                               all          modular DocBook DSSSL stylesheets, for print and HTML`
`ii  libcurl4-openssl-dev:amd64           7.38.0-4+deb8u4                      amd64        development files and documentation for libcurl (OpenSSL flavour)`
`ii  libgnutls-openssl27:amd64            3.3.8-6+deb8u3                       amd64        GNU TLS library - OpenSSL wrapper`
`ii  libssl-dev:amd64                     1.0.1t-1+deb8u5                      amd64        Secure Sockets Layer toolkit - development files`
`ii  libssl-doc                           1.0.1t-1+deb8u5                      all          Secure Sockets Layer toolkit - development documentation`
`ii  libssl1.0.0:amd64                    1.0.1t-1+deb8u5                      amd64        Secure Sockets Layer toolkit - shared libraries`
`rc  libxmlsec1-openssl                   1.2.20-2+b1                          amd64        Openssl engine for the XML security library`
`ii  openssl                              1.0.1t-1+deb8u5                      amd64        Secure Sockets Layer toolkit - cryptographic utility`
`ii  openssl-blacklist                    0.5-3                                all          Blacklists for  OpenSSL RSA keys and tools`
`ii  openssl-blacklist-extra              0.5-3                                all          Non-default blacklists of OpenSSL RSA keys`
`ii  python-openssl                       0.14-1                               all          Python 2 wrapper around the OpenSSL library`
`ii  python3-openssl                      0.14-1                               all          Python 3 wrapper around the OpenSSL library`
`ii  ssl-cert                             1.0.35                               all          simple debconf wrapper for OpenSSL`

**Comment by dedm** [comment]
Looks like some of the modules/libraries we use (see https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/requirements) are a little bit outdated and don't work properly with new Debian. 

Will work on that issue. 

Thanks for the report!

**Comment by dedm** [comment]
@Knight1 

After testing on a Debian 8.6 container, we can't reproduce this problem. It seems like this isn't related to Debian 8.6, but rather is a conflict between installed python-cryptography and python-cffi versions.

Multiple people online have reported getting the same strange error message, and this bug report (https://bugs.launchpad.net/devstack/+bug/1484870) recommends uninstalling python-cffi and reinstalling it with pip as a workaround.

May I ask you to try this workaround?

**Comment by Knight1** [comment]
@dedm 

Hey, thank you for this info.
After removing and installing the agent because of this bug
`Setting up nginx-amplify-agent (0.40-2~jessie) ...
dpkg: error processing package nginx-amplify-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 nginx-amplify-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)`

I did 
apt-get remove python-cffi
pip install cffi cryptography

Agent is online and reporting.
Thank you very much for you support!

**Comment by dedm** [comment]
@Knight1  thank you for reporting that bug! Glad we could help.
