### ISSUE TITLE
Amplify-agent is too slow to process logs

### ISSUE THREAD

**Issue by gugu** [nginxinc/nginx-amplify-agent#40]
We have nginx with 1500 req/second (mostly cached) and amplify-agent uses 100% CPU all the time.

Do you plan to rewrite critical log processing part to something faster, like C or golang?

**Comment by dedm** [comment]
Hi @gugu! 

In general, 1.5k rps is not too heavy load for amplify agent. It should not use 100% CPU in this case. 

Could you please provide us more information to solve the problem:
- OS name/version 
- Used hardware (CPU, Memory, HDD)
- Is this CPU load permanent or occasionally 
- Debug log for 20-30 minutes https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#logging
- The output from ps/top/other utilities
- How many log files do you have
- Used log_formats and examples of log entries.

Our support team wrote you an email with the same contents, so feel free to reply here or via email.

Best,
Mike
