### ISSUE TITLE
Agent`s config parser find location /user and don`t start

### ISSUE THREAD

**Issue by kacuragi87** [nginxinc/nginx-amplify-agent#42]
Have a nice day! 

Try update agent version. Config nginx.conf have location "/user"

[user@host ~]# /etc/init.d/amplify-agent start
Starting nginx-amplify-agent: chown: wrong user: «{»
chown: wrong user: «{»
chown: wrong user: «{»
runuser: user {  not exist

[user@host ~]# rpm -qa nginx-amplify-agent
nginx-amplify-agent-0.41-2.el6.x86_64

[user@host ~]# grep 'user {' /etc/nginx/nginx.conf
        location /user { proxy_pass web_backend; }

**Comment by dedm** [comment]
Hi @kacuragi87 !

May I kindly ask you to share your nginx config? The part of it with "user" directive, not "location".

**Comment by dedm** [comment]
@kacuragi87 ?

**Comment by kacuragi87** [comment]
Sorry, @dedm 

"user" directive is absent in config. I try add and problem went away... but before optimize some locations, location "/user" was included from another file, user not defined and that worked!

**Comment by dedm** [comment]
@kacuragi87 may I close this issue then?
