### ISSUE TITLE
Agent writes UUID to configuration file

### ISSUE THREAD

**Issue by cdarwin** [nginxinc/nginx-amplify-agent#44]
This breaks configuration management tools such as Chef, Puppet, and Salt. Standard convention for configuration management tools is to watch a configuration file and restart or reload the associate service on changes. According to the current implementation and [documentation](https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#changing-the-hostname-and-uuid) the `credentials.uuid` attribute is not intended to be user configurable and should be removed from the configuration file altogether.

**Comment by eric-brechemier** [comment]
Also, having the UUID in the configuration file requires extra care when updating the config from a script. We usually overwrite configuration files completely to use the latest version, which would cause the loss of the UUID in this case.

**Comment by gshulegaard** [comment]
Thanks for the input guys!  This is on our radar...I made sure we have a ticket in our queue.  We will update here once we make an appropriate change.

**Comment by dedm** [comment]
https://github.com/nginxinc/nginx-amplify-agent/commit/4299c79eab210e5201f4776fdeccb9364f9538fc
