### ISSUE TITLE
Error when nginx does not installed on default Path

### ISSUE THREAD

**Issue by cleberjsantos** [nginxinc/nginx-amplify-agent#51]
The error occurred here https://github.com/nginxinc/nginx-amplify-agent/blob/master/amplify/agent/managers/nginx.py#L196

**Error:** `2017-06-13 09:11:00,384 [61318] supervisor failed to find running nginx via ps xao pid,ppid,command | grep 'nginx[:]'`

**Solution:**

```diff

- ps_cmd = "ps xao pid,ppid,command | grep 'nginx[:]'"
+ ps_cmd = "ps xao pid,ppid,command | grep 'nginx'"

```

**Comment by dedm** [comment]
Hi, @cleberjsantos !

May I kindly ask you to share your ps output for the original command and for your suggestion?

**Comment by cleberjsantos** [comment]
I'm running one instance only in this server, bellow my ps output:

``` log
root@xxx:/home/cleber# ps xao pid,ppid,command | grep 'nginx'
60773  1126 /var/web/buildout/etc/../parts/nginx-build/sbin/nginx -c /var/web/buildout/etc/../parts/nginx/nginx.conf
```

**Comment by dedm** [comment]
so as I see you run it manually, correct?

**Comment by cleberjsantos** [comment]
I'm use an installation based in `buildout` and managed by `supervisord`, but, yes, we can say that it is manual or out of standard path of installation.

**Comment by dedm** [comment]
So, it looks like this installation runs nginx using a special directive `master_process off;`, which is not recommended in any production environment. This directive was invented only for debugging. Can you modify nginx config file and remove this directive?

**Comment by cleberjsantos** [comment]
Woooow. Yes, this was the problem :( Sorry
