### ISSUE TITLE
install.sh check to see if nginx on exclude list /etc/yum.conf

### ISSUE THREAD

**Issue by centminmod** [nginxinc/nginx-amplify-agent#52]
On custom LEMP stacks some folks source install Nginx and exclude nginx package via /etc/yum.conf but this prevents nginx-amplify-agent from installing as it matches the exclude = nginx.

Simple change in install.sh can be made to check for this https://community.centminmod.com/threads/nginx-amplify-open-source-monitoring-service.4963/page-4#post-50859 when nginx listed in exclude line

    grep -w nginx /etc/yum.conf
    exclude=*.i386 *.i586 *.i686 nginx* php* mysql*

change line 412 of install.sh as at 14/06/17 to

```
if [[ "$(grep -w nginx /etc/yum.conf)" ]]; then
  install_cmd="yum ${assume_yes} install --disableexcludes=main"
else
  install_cmd="yum ${assume_yes} install"
fi
```

previously mentioned at https://github.com/nginxinc/nginx-amplify-agent/issues/8

> nginx -V
> nginx version: nginx/1.13.1
> built by gcc 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC) 
> built with OpenSSL 1.0.2l  25 May 2017
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-ljemalloc -lpcre -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -gsplit-dwarf' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-compat --with-http_stub_status_module --with-http_secure_link_module --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_pagespeed-1.12.34.2-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.31 --add-module=../echo-nginx-module-0.60 --add-module=../redis2-nginx-module-0.14 --add-module=../ngx_http_redis-0.3.7 --add-dynamic-module=../lua-nginx-module-0.10.9rc5 --add-module=../memc-nginx-module-0.18 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.32 --with-pcre=../pcre-8.40 --with-pcre-jit --with-zlib=../zlib-1.2.11 --with-http_ssl_module --with-http_v2_module --add-module=../http2-push-nginx-module --with-openssl=../openssl-1.0.2l

**Comment by ptreyes** [comment]
So, this should be already in the updated install.sh. Thanks!
