### ISSUE TITLE
Can't access the following files: /usr/share/nginx/modules/

### ISSUE THREAD

**Issue by gemal** [nginxinc/nginx-amplify-agent#56]
```
Warning – Can't access the following files:
/usr/share/nginx/modules/	OSError: No such file or directory
```

I'm on a amazon ec2 standard installed nginx

not sure it should be reported as a warning?

**Comment by ptreyes** [comment]
Hi,

This basically means that the agent can't access this directory, but it's probably referenced in the nginx.conf? Shouldn't affect much.

More here:

https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#overriding-the-effective-user-id
https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#what-to-check-if-the-agent-isnt-reporting-metrics

Also, it's better to address such issues via the Intercom/Amplify support chat, if possible :)
