### ISSUE TITLE
PHP-FPM statistics don't appear to work for remote PHP

### ISSUE THREAD

**Issue by flxsource** [nginxinc/nginx-amplify-agent#61]
When using a remote PHP-FPM instance via TCP (as in a docker network) the Agent doesn't seem to attempt to collect the stats. This is despite `cgi-fcgi` being able to correctly fetch the metrics.

**Comment by ptreyes** [comment]
Is this happening with the latest agent? (0.44-2)

**Comment by flxsource** [comment]
@ptreyes Yes, 0.44-2

**Comment by ptreyes** [comment]
Ok, so it looks like the agent is running in one container, and php-fpm is in another one. You should enable the second agent in the php-fpm container. More on Amplify/Docker container here: https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#using-the-agent-with-docker
