### ISSUE TITLE
Individual pool not showing up

### ISSUE THREAD

**Issue by Sir-Will** [nginxinc/nginx-amplify-agent#62]
I have an individual pool for php7.2-fpm which is not showing up on amplify while the main pool is showing up.
The metrics can be successfully queried with
```
SCRIPT_NAME=/status SCRIPT_FILENAME=/status QUERY_STRING= REQUEST_METHOD=GET cgi-fcgi -bind -connect /var/run/php/php7.2-fpm-mcserverlists.sock
```
There are no errors in the agent.log

What could be the issue?
Does amplify merge the pools because it's using the same php fpm? Is there a way to separate them?

**Comment by achawla2012** [comment]
Here are list of metrics that Amplify currently supports and caveats that might be. https://docs.nginx.com/nginx-amplify/metrics-metadata/other-metrics/

I am closing this for now. Let us know if you have still have issues around, please submit agent log in debug for us to troubleshoot further.
