### ISSUE TITLE
supervisor could not read /etc/letsencrypt/live/<domain>/fullchain.pem (maybe permissions?)

### ISSUE THREAD

**Issue by riegercloud** [nginxinc/nginx-amplify-agent#67]
The Amplify Agent (v. 045.2 / Ubtunu 16.04.3 LTS x64) was installed successfully from scratch today.

> Config file /etc/amplify-agent/agent.conf is OK

The agent is not able to read the letsencrypt fullchain.pem file. i already changed the folder permissions to 

root:root
-or- root:www-data
-or- www-data:www-data
and restarted the agent, but the errors still occur in both log files:

(1) in nginx/error.log:
> 2017/08/20 18:26:57 [emerg] 16583#16583: BIO_new_file("/etc/letsencrypt/live/nc.c-rieger.de/fullchain.pem") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/nc.c-rieger.de/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)

(2) in agent.log:
> 2017-08-20 18:26:57,864 [16542] supervisor could not read /etc/letsencrypt/live/nc.c-rieger.de/fullchain.pem (maybe permissions?)

The amplify web-gui is configured as shown below:
![grafik](https://user-images.githubusercontent.com/20593693/29496694-4f3087de-85d8-11e7-921d-56e6fae01ca4.png)

The current information:
![grafik](https://user-images.githubusercontent.com/20593693/29496679-18e99648-85d8-11e7-80ae-2b77f4f071f4.png)

How could this be solved and how can the timesetting be adjusted from GTM to e.g. GTM+2 (Europe/Berlin)? I would really appreciate any assistance.
Thx in advance, Carsten

**Comment by riegercloud** [comment]
![grafik](https://user-images.githubusercontent.com/20593693/29532239-5db7ce1e-86ac-11e7-9600-e11b6190499e.png)

**Comment by riegercloud** [comment]
![grafik](https://user-images.githubusercontent.com/20593693/29532252-7e9ddac4-86ac-11e7-8b1b-a65a3a1d5b9c.png)

**Comment by riegercloud** [comment]
![grafik](https://user-images.githubusercontent.com/20593693/29532671-78ce3164-86ae-11e7-9aa4-dcc16b067904.png)

![grafik](https://user-images.githubusercontent.com/20593693/29532685-8adaddda-86ae-11e7-83a5-8d04b0f33d6d.png)

**Comment by riegercloud** [comment]
chown -R www-data:www-data /etc/letsencrypt/live
chown -R www-data:www-data /etc/letsencrypt/archive

**Comment by gshulegaard** [comment]
Thanks for the solution update!

**Comment by concatime** [comment]
I don't think you should change the owner (let it root), but rather change only the group to www-data, and adjust the 6X0 or 7X0 permissions. If X is 2, nginx can normally read the file.
PS: Sorry for the necrobump.

**Comment by gshulegaard** [comment]
No problem with the Necrobump!  Generally good advice.

**Comment by andreapernici** [comment]
Yes it doesn't look a permission issue cause everything is fine from a permission perspective. I have the same issue and even giving all 777 doesn't change the log.

**Comment by gshulegaard** [comment]
Hi @andreapernici, it seems like you are having a new issue!  Please feel free to create a new issue with some log and system details.

**Comment by gshulegaard** [comment]
SSL Certificate Analysis such as expiration warnings and server name matches requires that the Amplify Agent read the ssl cert/key in order to compare the information there with you NGINX configuration.  This is an _optional_ analysis and can be configured in the Amplify UI globally and also for individual systems.

**Comment by Nicholi** [comment]
A very necropost, but I've found you only need to open permissions on `/etc/letsencrypt/archive` and `/etc/letsencrypt/live`. As certbot will use root:root 0700 permissions on these directories by default, so your cert/key files are protected from anything other than root. Even though the permissions under this directory are more permissive, 0700 prevents anyone other than root from getting through.

My workaround without changing too much ownership/permissions was to just use extended ACLs as such:
```
setfacl -m 'u:nginx:rx' /etc/letsencrypt/archive /etc/letsencrypt/live
```
