### ISSUE TITLE
open() "/var/run/nginx.pid" failed (13: Permission denied)

### ISSUE THREAD

**Issue by riegercloud** [nginxinc/nginx-amplify-agent#68]
Amplify agent v. 045.2 on Ubtunu 16.04.3 LTS x64, NGINX 1.13.4
Even when starting amplify the followwing warning/error will be thrown:

> 2017/08/28 20:31:29 [emerg] 28590#28590: open() "/var/run/nginx.pid" failed (13: Permission denied)
> 2017/08/28 20:32:32 [warn] 28895#28895: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1

The permissions of thiss pid were set as shown below:

> root@nc:/usr/local/src# ls -lsah /var/run/nginx.pid
> 4,0K -rw-r--r-- 1 root root 6 Aug 28 20:32 /var/run/nginx.pid

NGINX 1.13.4 was configured for running as www-data:

> user www-data;

How to avoid these messages?

**Comment by riegercloud** [comment]
...

> Could you please provide the output of the following command:
> ps aux | grep nginx
> sudo service nginx status
> Also share the agent.conf file.

...
[output4nginx.txt](https://github.com/nginxinc/nginx-amplify-agent/files/1266318/output4nginx.txt)
[nginx.error.log.txt](https://github.com/nginxinc/nginx-amplify-agent/files/1266322/nginx.error.log.txt)
[agent.conf.txt](https://github.com/nginxinc/nginx-amplify-agent/files/1266323/agent.conf.txt)

**Comment by riegercloud** [comment]
> The nginx master process has root permissions but Amplify-agent periodically performs the command 'nginx -t' by a non-root user. That is the reason for these errors in the error.log:
>So, you may just ignore these errors.

**Comment by sumitramteke** [comment]
Simple rebooting system solved my issue

**Comment by karugara** [comment]
excelent!! it works for me too, i cause i execute nginx -t like simple user instead root user, also just with sudo and reboting the terminal.
