### ISSUE TITLE
typeerror: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by RyanMesser** [nginxinc/nginx-amplify-agent#72]
Hi

On alpine docker, I get on the setup.py
typeerror: 'dict_keys' object is not subscriptable

I had to use python3 and python3-dev but get the above error..

I tried using python2 and python2-dev but get a different error that states that the install can't be done with python 2.7.

Any ideas :)?

**Comment by achawla2012** [comment]
There are no prebuilt packages available for Alpine, latest agent version (1.8.0) that now comes with Python3 is known to work with at least Alpine 3.13, 3.14, and 3.15. You can use https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh for getting it to work.

I am closing this ticket for now. Please reopen if you still see an issue.
