### ISSUE TITLE
Agent stopped reading nginx logs

### ISSUE THREAD

**Issue by ingria** [nginxinc/nginx-amplify-agent#75]
I've had Agent runnig for a couple of month, but suddenly it stopped reading the logs (both errors and access, both from default /var/log/nginx and my custom locations). As result, I don't have access to any of log-related metrics:

![shot](https://user-images.githubusercontent.com/2178368/31918722-de29f266-b866-11e7-8680-f766a130462d.png)

I tried re-installing the Agent, changing the logs' paths in nginx.conf, re-adding the server in the Agent web dashboard, chmodding the logs files to 777, disabling the logging buffereing and log format, but nothing helps.

I'm using Ubuntu 16.04 EC2, nginx 1.12.2.

**Comment by gshulegaard** [comment]
Hi @ingria, are there any errors in the agent log (`/var/log/amplify-agent/agent.log`)?

**Comment by ingria** [comment]
@gshulegaard no, just routine entries:

```
2017-11-08 16:25:08,328 [1518] supervisor [***] post https://receiver.amplify.nginx.com:443/1.3/***/agent/ 200 86 4 0.186
2017-11-08 16:26:07,584 [1518] bridge_manager [***] post https://receiver.amplify.nginx.com:443/1.3/***/update/ 202 2771 0 0.181
```

**Comment by gshulegaard** [comment]
Could you configure agent with `DEBUG` logging and check that?  Log configuration should be in `/etc/amplify-agent/agent.conf`.

If nothing jumps out in debug logging, it may be best to reach out via Intercom so we can put you into our support process and we can share potentially sensitive system info.

**Comment by ingria** [comment]
I cannot see any logs-related errors. Here's the output (cleaned-up):

http://pastebin.ubuntu.com/25922645/

I don't mind contacting you via Intercom, what do I have to do?

**Comment by gshulegaard** [comment]
Hi @ingria thanks for that snippet, unfortunately it isn't really long enough to get a good grasp on the agent behavior.

For Intercom, in our web user interface there should be a chat circle widget in the lower right hand corner:

![screen shot 2017-11-08 at 12 55 27 pm](https://user-images.githubusercontent.com/8593818/32624476-4495a3f4-c53e-11e7-9e45-3059238921d8.png)

**Comment by ingria** [comment]
It seems that the problem fixed itself after agent v0.47-1 has been released ¯\_(ツ)_/¯.

Thanks for the support anyway.

**Comment by gshulegaard** [comment]
Thanks for taking the time to report!

**Comment by gshulegaard** [comment]
Thanks for taking the time to report!
