### ISSUE TITLE
Adding public key ... Failed writing body  failed

### ISSUE THREAD

**Issue by fasalgad** [nginxinc/nginx-amplify-agent#75]
Installation error on Debian 10

 --- This script will install the NGINX Amplify Agent package ---

  1. Checking admin user ... root, ok.
  2. Checking API key ... using [API_KEY]
  3. Checking if uuid should be stored in the config ... False
  4. Checking Python ... found python 2.7
  5. Checking OS compatibility ... debian detected.
  6. Adding public key ...(23) Failed writing body
 failed.

The main error is : 
`curl -fs https://nginx.org/keys/nginx_signing.key | sudo apt-key add - > /dev/null 2>&1`

Solution:

`sudo apt-get update && apt-get install -y gnupg2`

and then:

`curl -sS -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh && API_KEY='YOUR_API_KEY' sh ./install.sh`

**Comment by achawla2012** [comment]
I am closing this for now. Please feel free to open this issue if  you still have issue with latest version.
