### ISSUE TITLE
account for yum.conf excludes=nginx*

### ISSUE THREAD

**Issue by centminmod** [nginxinc/nginx-amplify-agent#8]
Some folks source compile Nginx so exclude the nginx\* package in their yum.conf. This seems to prevent nginx-amplify-agent yum package from installing https://community.centminmod.com/posts/20812/

maybe even rename package to `amplify-agent` ?

**Comment by ptreyes** [comment]
Thanks for the report! Just curious, what's the reason for filtering out "nginx*"? Would the workaround described in the above mentioned post work for the centminmod community you think?

**Comment by centminmod** [comment]
Yeah the workaround outlined in link works for Centmin Mod LEMP stack. The reason is to prevent accidental install of nginx yum package and conflict with source compiled nginx version.

Of course you do away with the problem altogether if the yum package was renamed `amplify-agent` instead and well it's shorter :)

**Comment by ptreyes** [comment]
So, this should be already in the updated install.sh. Thanks!
