### ISSUE TITLE
Rocky Linux 8 support in the install.sh script

### ISSUE THREAD

**Issue by makhomed** [nginxinc/nginx-amplify-agent#82]
Rocky Linux 8 is 1:1 binary compatible RHEL 8 clone, created from some source files as RHEL 8 itself.

Can you please add support for Rocky Linux 8 into install.sh script?

If I manually create file `/etc/yum.repos.d/nginx-amplify.repo` with content:
```
[nginx-amplify]
name=nginx amplify repo
baseurl=http://packages.amplify.nginx.com/py3/rhel/8/$basearch
gpgcheck=1
enabled=1
```
I can install `nginx-amplify-agent` using command `yum install nginx-amplify-agent`.
After installation `amplify-agent` service can be started and run on the Rocky Linux 8.6

**Comment by achawla2012** [comment]
Closing this issue as @defanator changes has been merged. Feel free to reopen ticket if have any questions
