### ISSUE TITLE
Some files are missed in the latest release

### ISSUE THREAD

**Issue by SpiderX** [nginxinc/nginx-amplify-agent#82]
Hello.

The latest tarball lacks of stream.py, stream_upstream.py and slab.py from amplify/agent/collectors/plus/util/

Please, make a release that includes [this](https://github.com/nginxinc/nginx-amplify-agent/commit/d24fc26ade4df334f49ec3d51998a2219e89f301) commit

**Comment by dedm** [comment]
Thank you @SpiderX ! 
We released a new version, so please use 1.0.1: https://github.com/nginxinc/nginx-amplify-agent/releases/tag/v1.0.1-1
