### ISSUE TITLE
 Bad file descriptor in version 1.1.0-1

### ISSUE THREAD

**Issue by zahariash** [nginxinc/nginx-amplify-agent#85]
After upgrade to nginx-amplify-agent-1.1.0-1.amzn1.x86_64 service won't start.  Amazon Linux AMI 2017.09.                    

/var/log/amplify-agent/agent.log:

> 2018-02-08 11:02:40,017 [20364] supervisor uncaught exception during run time
> Traceback (most recent call last):
>   File "/usr/bin/nginx-amplify-agent.py", line 151, in <module>
>     daemon_runner.do_action()
>   File "/usr/lib/python2.7/dist-packages/amplify/daemon/runner.py", line 267, in do_action
>     func(self)
>   File "/usr/lib/python2.7/dist-packages/amplify/daemon/runner.py", line 186, in _start
>     self.app.run()
>   File "/usr/lib/python2.7/dist-packages/amplify/agent/supervisor.py", line 177, in run
>     time.sleep(5.0)
>   File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 194, in sleep
>     hub.wait(loop.timer(seconds, ref=ref))
>   File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 627, in wait
>     result = waiter.get()
>   File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 875, in get
>     return self.hub.switch()
>   File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 606, in switch
>     return greenlet.switch(self)
> SystemError: (libev) epoll_wait: Bad file descriptor
> 2018-02-08 11:02:40,022 [20364] DummyThread-2 failed POST "https://receiver.amplify.nginx.com:443/1.3/[...CUT...]/update/", exception: "(libev) epoll_wait: In valid argument"
> 2018-02-08 11:02:40,022 [20364] DummyThread-2 [None] post https://receiver.amplify.nginx.com:443/1.3/[...CUT...]/update/ 500 43 0 0.001
> 2018-02-08 11:02:40,022 [20364] DummyThread-2 failed to push data due to SystemError
> 2018-02-08 11:02:40,022 [20364] DummyThread-2 agent stopped, version=1.1.0-1 pid=20364 uuid=5df1f6ead4a35e4ebbc947890fb2517a

**Comment by defanator** [comment]
@zahariash thank you for the report, we can confirm that we were able to reproduce the issue. As of now, you can downgrade the package (`yum downgrade nginx-amplify-agent`) as previous version is not affected.
