### ISSUE TITLE
Amplify alert and mark server down if the server behind NAT.

### ISSUE THREAD

**Issue by draskolnikova** [nginxinc/nginx-amplify-agent#9]
Is it normal? The box can reach out the internet.

**Comment by dedm** [comment]
It seems like your server doesn't send updates to the cloud. Can you provide /var/log/amplify-agent/agent.log?

**Comment by draskolnikova** [comment]
@dedm hello!
my bad, the resolver are empty and the agent tried to look up fqdn.
marked as close and not bug.

thank you! :smile:
