### ISSUE TITLE
Service wont start - 404 Client Error: NOT FOUND for url

### ISSUE THREAD

**Issue by djob** [nginxinc/nginx-amplify-agent#90]
Hi,

i recently installed agent on my DO droplet and after whole day still no data.

**agent.log**:
2018-03-08 04:46:46,374 [4594] MainThread failed POST "https://receiver.amplify.nginx.com:443/1.3/xxxxxxxxxxxxxxxxx/agent/", exception: "404 Client Error: NOT FOUND for url: https://receiver.amplify.nginx.com:443/1.3/xxxxxxxxxxxxxxxxx/agent/"

**tried to restart agent, systemctl status:**

amplify-agent[4561]: Apologies and bear with us.
amplify-agent[4561]: We will try to establish a connection once again in a minute.
amplify-agent[4561]: Could not connect to cloud via url https://receiver.amplify.nginx.com:443/1.3
amplify-agent[4561]: We will try to establish a connection once again in a minute.
amplify-agent[4561]: Could not connect to cloud via url https://receiver.amplify.nginx.com:443/1.3
amplify-agent[4561]: Giving up after three attempts...
systemd[1]: amplify-agent.service: Control process exited, code=exited status=1
systemd[1]: Failed to start LSB: Stop/start nginx-amplify-agent.
systemd[1]: amplify-agent.service: Unit entered failed state.
systemd[1]: amplify-agent.service: Failed with result 'exit-code'.

**Traceroute:**
traceroute receiver.amplify.nginx.com
traceroute to receiver.amplify.nginx.com (35.162.241.164), 30 hops max, 60 byte packets
 1  46.101.128.254 (46.101.128.254)  0.809 ms 46.101.128.253 (46.101.128.253)  0.792 ms 46.101.128.254 (46.101.128.254)  0.810 ms
 2  138.197.250.146 (138.197.250.146)  0.851 ms 138.197.250.160 (138.197.250.160)  0.785 ms 138.197.250.144 (138.197.250.144)  0.767 ms
 3  ffm-b4-link.telia.net (80.239.128.20)  0.827 ms ffm-b4-link.telia.net (80.239.128.22)  0.725 ms  0.766 ms
 4  ffm-bb3-link.telia.net (62.115.120.1)  0.941 ms ffm-bb4-link.telia.net (62.115.123.180)  1.030 ms ffm-bb3-link.telia.net (62.115.124.74)  0.919 ms
 5  nyk-bb3-link.telia.net (213.155.131.145)  123.993 ms prs-bb4-link.telia.net (62.115.122.138)  91.191 ms nyk-bb3-link.telia.net (213.155.131.145)  123.993 ms
 6  chi-b21-link.telia.net (80.91.246.162)  116.005 ms ldn-bb2-link.telia.net (62.115.114.228)  90.759 ms ffm-bb4-link.telia.net (62.115.116.159)  87.411 ms
 7  ldn-b5-link.telia.net (213.155.132.197)  96.950 ms  96.903 ms nyk-b5-link.telia.net (80.91.254.14)  88.315 ms
 8  nyk-bb4-link.telia.net (80.91.251.100)  80.389 ms nyk-bb3-link.telia.net (62.115.115.0)  91.258 ms nyk-bb4-link.telia.net (80.91.251.100)  80.811 ms
 9  chi-b21-link.telia.net (80.91.246.162)  111.505 ms nyk-bb3-link.telia.net (62.115.135.94)  93.852 ms chi-b21-link.telia.net (80.91.246.162)  111.533 ms
10  chi-b21-link.telia.net (80.91.246.162)  114.355 ms  114.349 ms sea-b2-link.telia.net (62.115.117.48)  153.976 ms
11  sea-b1-link.telia.net (62.115.115.2)  158.468 ms *  158.465 ms
12  amazon-ic-307562-sea-b1.c.telia.net (213.248.92.242)  152.826 ms amazon-ic-307566-sea-b1.c.telia.net (62.115.47.198)  145.731 ms *
13  * * *
14  * * *
15  * * *
16  * * *
17  54.239.48.181 (54.239.48.181)  174.740 ms * *
18  * * *
19  * * *
20  * * *
21  * 54.239.48.181 (54.239.48.181)  170.186 ms  170.202 ms
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by dedm** [comment]
was fixed during the conversation with the support team
