### ISSUE TITLE
Wrong 'python-dev' package detection on SuSE

### ISSUE THREAD

**Issue by MikhailKasimov** [nginxinc/nginx-amplify-agent#92]
Hello!

Build-script in use:
[1] https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh

When choosing ```2``` in OS detection menu (```SLES 12```), ```python-dev``` package detection mistakenly says ```yes```,
![nginx_amplify_python_devel_package_wrong_detection](https://user-images.githubusercontent.com/7167300/38156670-69503024-3488-11e8-8c22-c00169db97e1.png)

because there is no ```python-dev``` package in SuSE, ```python-devel``` only.
![zypper_python_devel_package](https://user-images.githubusercontent.com/7167300/38156658-546147c0-3488-11e8-8471-770eda96dbad.png)

And further ```nginx-amplify-agent``` building process gets a couple of error-messages on ```Python.h``` file is not exist.

After installing ```python-devel``` package via ```zypper install python-devel``` command, ```nginx-amplify-agent``` building process gets ```OK```.

P.S. BTW, ```SLES 12``` option can be bravely generalized to ```openSUSE/SLE```, because ```install-source.sh``` script works fine with ```openSUSE Leap 42.3```, on which ```install-source.sh``` is under current tests.

And this also is applicable for installation part of script:

```# SLES 12
    2)
        os="sles12"

        install_warn1
        check_packages

        test "${found_python}" = "no" && ${sudo_cmd} zypper install python
        test "${found_python_dev}" = "no" && ${sudo_cmd} zypper install python-dev
        test "${found_git}" = "no" && ${sudo_cmd} zypper install git
        test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} dnf -y install wget
        ;;
```

Here:
1) ```zypper install python-dev``` should be changed on to ```zypper install python-devel```
2) ``` test "${found_python_dev}"``` --> ```test "${found_python_devel}"```

Thanks!

**Comment by defanator** [comment]
@MikhailKasimov thanks for reporting, this has been fixed in latest `install-source.sh`.
