### ISSUE TITLE
Wrong 'dnf -y install wget' command for SuSE

### ISSUE THREAD

**Issue by MikhailKasimov** [nginxinc/nginx-amplify-agent#93]
Hello!

Build-script in use:
[1] https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh

```# SLES 12
    2)
        os="sles12"

        install_warn1
        check_packages

        test "${found_python}" = "no" && ${sudo_cmd} zypper install python
        test "${found_python_dev}" = "no" && ${sudo_cmd} zypper install python-dev
        test "${found_git}" = "no" && ${sudo_cmd} zypper install git
        test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} dnf -y install wget
        ;;
```

Here ```dnf -y install wget``` is wrong, because ```dnf``` package-manager is applicable for ```Red Hat/Fedora/CentOS``` dstros, not for ```SuSE```.

BTW, ```-y``` option for ```zypper``` package-manager is also applicable.

So, finally, this code-snippet should be like:

```
...
  test "${found_python}" = "no" && ${sudo_cmd} zypper -y install python
        test "${found_python_dev}" = "no" && ${sudo_cmd} zypper -y install python-devel
        test "${found_git}" = "no" && ${sudo_cmd} zypper -y install git
        test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} zypper -y install wget
```
For ```test "${found_python_dev}"``` string see #92 

Thanks!

**Comment by defanator** [comment]
@MikhailKasimov thanks for reporting, this has been fixed in latest `install-source.sh`.
