### ISSUE TITLE
Wrong 'dnf -y install wget' command for FreeBSD

### ISSUE THREAD

**Issue by MikhailKasimov** [nginxinc/nginx-amplify-agent#94]
Hello!

Build-script in use:
[1] https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh

```
1)
        os="freebsd"

        install_warn1
        check_packages

        test "${found_python}" = "no" && ${sudo_cmd} pkg install python
        test "${found_git}" = "no" && ${sudo_cmd} pkg install git
        test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} dnf -y install wget
```
Here ```dnf -y install wget``` is wrong, because ```dnf``` package-manager is applicable for ```Red Hat/Fedora/CentOS``` Linux distros.

This should be

```test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} pkg install wget``` 

I suppose.

Thanks!

**Comment by defanator** [comment]
@MikhailKasimov thanks for reporting, this has been fixed in latest `install-source.sh`.
