### ISSUE TITLE
Wrong 'dnf -y install wget' command for Alpine

### ISSUE THREAD

**Issue by MikhailKasimov** [nginxinc/nginx-amplify-agent#95]
Hello!

Build-script in use:
[1] https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/install-source.sh

```
3)
        os="alpine37"

        install_warn1
        check_packages

        test "${found_python}" = "no" && ${sudo_cmd} apk add --no-cache python && py_command="python"
        test "${found_python_dev}" = "no" && ${sudo_cmd} apk add --no-cache python-dev
        test "${found_git}" = "no" && ${sudo_cmd} apk add --no-cache git
        ${sudo_cmd} apk add --no-cache util-linux procps
        test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} dnf -y install wget
        test "${found_gcc}" = "no" && ${sudo_cmd} apk add --no-cache gcc musl-dev linux-headers
```
Here ```dnf -y install wget``` is wrong, because ```dnf``` package-manager is applicable for ```Red Hat/Fedora/CentOS``` Linux distros.

This should be:

```test "${found_wget}" = "no" -a "${found_curl}" = "no" &&  ${sudo_cmd} apk add --no-cache wget``` 

I suppose.

Thanks!

**Comment by defanator** [comment]
@MikhailKasimov thanks for reporting, this has been fixed in latest `install-source.sh`.
