### ISSUE TITLE
permission not read

### ISSUE THREAD

**Issue by Owned67** [nginxinc/nginx-amplify-agent#98]
Hello,

i've try to chown www-data user to /etc/letsencrypt/live folder, chmod 755 /etc/letsencrypt/live but it's same problem...

on log file:

```
2023-06-11 07:59:32,896 [242288] supervisor ssl certificate found /etc/letsencrypt/live/myndd.eu/fullchain.pem
2023-06-11 07:59:32,896 [242288] supervisor could not read /etc/letsencrypt/live/myndd.eu/fullchain.pem (maybe permissions?)
```

someone have a suggestion please?

Thanks

**Comment by achawla2012** [comment]
@Owned67 were you able to resolve this issue? From the log output it looks PEM file most likely not accessible by the agent process. I would move the pem files into a directory that is accessible by the nginx user.

**Comment by Owned67** [comment]
not solved, i've completly forgot this xD

always getting same problem...

I've chown to nginx user the folder letsencrypt with recursive...

waiting amplify for checking log so.


not solved, really weird, same error persist..

**Comment by Owned67** [comment]
Seems good now, for someone having issue:
`setfacl --recursive --modify u:www-data:rX,d:u:root:rX \
  /etc/letsencrypt/archive \
  /etc/letsencrypt/live
` and restart amplify agent
